||| The arith dialect's syntax, as the Idris side writes it: the enums
||| its ops, types and attributes take, and its types and attributes, which
||| IdrisMLIR.MLIR's types and attributes hold. Generated by idris-mlir-tblgen
||| -gen-idris-syntax from the dialect's ODS; `make build` writes it
||| (tools/dialects.sh). Do not edit.
module IdrisMLIR.Syntax.Arith

import IdrisMLIR.MLIR.Text

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace CmpFPredicate
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  public export
  data CmpFPredicate = AlwaysFalse | OEQ | OGT | OGE | OLT | OLE | ONE | ORD | UEQ | UGT | UGE | ULT | ULE | UNE | UNO | AlwaysTrue

export
Prelude.EqOrd.Eq CmpFPredicate where
  CmpFPredicate.AlwaysFalse == CmpFPredicate.AlwaysFalse = True
  CmpFPredicate.OEQ == CmpFPredicate.OEQ = True
  CmpFPredicate.OGT == CmpFPredicate.OGT = True
  CmpFPredicate.OGE == CmpFPredicate.OGE = True
  CmpFPredicate.OLT == CmpFPredicate.OLT = True
  CmpFPredicate.OLE == CmpFPredicate.OLE = True
  CmpFPredicate.ONE == CmpFPredicate.ONE = True
  CmpFPredicate.ORD == CmpFPredicate.ORD = True
  CmpFPredicate.UEQ == CmpFPredicate.UEQ = True
  CmpFPredicate.UGT == CmpFPredicate.UGT = True
  CmpFPredicate.UGE == CmpFPredicate.UGE = True
  CmpFPredicate.ULT == CmpFPredicate.ULT = True
  CmpFPredicate.ULE == CmpFPredicate.ULE = True
  CmpFPredicate.UNE == CmpFPredicate.UNE = True
  CmpFPredicate.UNO == CmpFPredicate.UNO = True
  CmpFPredicate.AlwaysTrue == CmpFPredicate.AlwaysTrue = True
  _ == _ = False

namespace CmpIPredicate
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
  public export
  data CmpIPredicate = Eq | Ne | Slt | Sle | Sgt | Sge | Ult | Ule | Ugt | Uge

export
Prelude.EqOrd.Eq CmpIPredicate where
  CmpIPredicate.Eq == CmpIPredicate.Eq = True
  CmpIPredicate.Ne == CmpIPredicate.Ne = True
  CmpIPredicate.Slt == CmpIPredicate.Slt = True
  CmpIPredicate.Sle == CmpIPredicate.Sle = True
  CmpIPredicate.Sgt == CmpIPredicate.Sgt = True
  CmpIPredicate.Sge == CmpIPredicate.Sge = True
  CmpIPredicate.Ult == CmpIPredicate.Ult = True
  CmpIPredicate.Ule == CmpIPredicate.Ule = True
  CmpIPredicate.Ugt == CmpIPredicate.Ugt = True
  CmpIPredicate.Uge == CmpIPredicate.Uge = True
  _ == _ = False

namespace FastMathFlags
  ||| Floating point fast math flags
  public export
  data FastMathFlags = Reassoc | Nnan | Ninf | Nsz | Arcp | Contract | Afn

export
Prelude.EqOrd.Eq FastMathFlags where
  FastMathFlags.Reassoc == FastMathFlags.Reassoc = True
  FastMathFlags.Nnan == FastMathFlags.Nnan = True
  FastMathFlags.Ninf == FastMathFlags.Ninf = True
  FastMathFlags.Nsz == FastMathFlags.Nsz = True
  FastMathFlags.Arcp == FastMathFlags.Arcp = True
  FastMathFlags.Contract == FastMathFlags.Contract = True
  FastMathFlags.Afn == FastMathFlags.Afn = True
  _ == _ = False

-- How the syntax below spells each FastMathFlags.
fastMathFlagsSpelling : FastMathFlags -> String
fastMathFlagsSpelling FastMathFlags.Reassoc = "reassoc"
fastMathFlagsSpelling FastMathFlags.Nnan = "nnan"
fastMathFlagsSpelling FastMathFlags.Ninf = "ninf"
fastMathFlagsSpelling FastMathFlags.Nsz = "nsz"
fastMathFlagsSpelling FastMathFlags.Arcp = "arcp"
fastMathFlagsSpelling FastMathFlags.Contract = "contract"
fastMathFlagsSpelling FastMathFlags.Afn = "afn"

-- How the syntax below spells a set of FastMathFlags: its bits, apart.
fastMathFlagsSpellings : List FastMathFlags -> String
fastMathFlagsSpellings [] = "none"
fastMathFlagsSpellings es = separated "," (map fastMathFlagsSpelling es)

namespace IntegerOverflowFlags
  ||| Integer overflow arith flags
  public export
  data IntegerOverflowFlags = Nsw | Nuw

export
Prelude.EqOrd.Eq IntegerOverflowFlags where
  IntegerOverflowFlags.Nsw == IntegerOverflowFlags.Nsw = True
  IntegerOverflowFlags.Nuw == IntegerOverflowFlags.Nuw = True
  _ == _ = False

-- How the syntax below spells each IntegerOverflowFlags.
integerOverflowFlagsSpelling : IntegerOverflowFlags -> String
integerOverflowFlagsSpelling IntegerOverflowFlags.Nsw = "nsw"
integerOverflowFlagsSpelling IntegerOverflowFlags.Nuw = "nuw"

-- How the syntax below spells a set of IntegerOverflowFlags: its bits, apart.
integerOverflowFlagsSpellings : List IntegerOverflowFlags -> String
integerOverflowFlagsSpellings [] = "none"
integerOverflowFlagsSpellings es = separated ", " (map integerOverflowFlagsSpelling es)

namespace RoundingMode
  ||| Floating point rounding mode
  public export
  data RoundingMode = ToNearestEven | Downward | Upward | TowardZero | ToNearestAway

export
Prelude.EqOrd.Eq RoundingMode where
  RoundingMode.ToNearestEven == RoundingMode.ToNearestEven = True
  RoundingMode.Downward == RoundingMode.Downward = True
  RoundingMode.Upward == RoundingMode.Upward = True
  RoundingMode.TowardZero == RoundingMode.TowardZero = True
  RoundingMode.ToNearestAway == RoundingMode.ToNearestAway = True
  _ == _ = False

------------------------------------------------------------------------------
-- Attributes
------------------------------------------------------------------------------

||| The arith dialect's attributes, one constructor each, named
||| after its C++ class; `ty` is the type of the types they hold, `at` of the
||| attributes.
public export
data ArithAttr : (ty : Type) -> (at : Type) -> Type where
  ||| `#arith.fastmath`: Floating point fast math flags
  FastMathFlagsAttr : (value : List FastMathFlags) -> ArithAttr ty at
  ||| `#arith.overflow`: Integer overflow arith flags
  IntegerOverflowFlagsAttr : (value : List IntegerOverflowFlags) -> ArithAttr ty at

||| The mnemonics of the arith dialect's attributes.
export
arithAttrMnemonics : List String
arithAttrMnemonics = ["fastmath", "overflow"]

||| The mnemonic of each of the arith dialect's attributes.
export
arithAttrMnemonic : ArithAttr ty at -> String
arithAttrMnemonic (FastMathFlagsAttr _) = "fastmath"
arithAttrMnemonic (IntegerOverflowFlagsAttr _) = "overflow"

||| The text of each of the arith dialect's attributes, the types it
||| holds written by `t`, the attributes by `a`.
export
arithAttrText : (t : ty -> String) -> (a : at -> String) -> ArithAttr ty at -> String
arithAttrText t a (FastMathFlagsAttr value) = fastConcat ["#arith.fastmath<", (fastMathFlagsSpellings value), ">"]
arithAttrText t a (IntegerOverflowFlagsAttr value) = fastConcat ["#arith.overflow<", (integerOverflowFlagsSpellings value), ">"]

