||| The idr dialect's syntax, as the Idris side writes it: the enums
||| its ops, types and attributes take, and its types and attributes, which
||| IdrisMLIR.MLIR's types and attributes hold. Generated by idris-mlir-tblgen
||| -gen-idris-syntax from the dialect's ODS; `make build` writes it
||| (tools/dialects.sh). Do not edit.
module IdrisMLIR.Syntax.Idr

import IdrisMLIR.MLIR.Text

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace CmpPredicate
  ||| a comparison of strings or bigs
  public export
  data CmpPredicate = Eq | Lt | Lte | Gt | Gte

export
Prelude.EqOrd.Eq CmpPredicate where
  CmpPredicate.Eq == CmpPredicate.Eq = True
  CmpPredicate.Lt == CmpPredicate.Lt = True
  CmpPredicate.Lte == CmpPredicate.Lte = True
  CmpPredicate.Gt == CmpPredicate.Gt = True
  CmpPredicate.Gte == CmpPredicate.Gte = True
  _ == _ = False

namespace Effect
  ||| what a call of a function may do
  public export
  data Effect = Io | Crash | Diverge

export
Prelude.EqOrd.Eq Effect where
  Effect.Io == Effect.Io = True
  Effect.Crash == Effect.Crash = True
  Effect.Diverge == Effect.Diverge = True
  _ == _ = False

-- How the syntax below spells each Effect.
effectSpelling : Effect -> String
effectSpelling Effect.Io = "io"
effectSpelling Effect.Crash = "crash"
effectSpelling Effect.Diverge = "diverge"

-- How the syntax below spells a set of Effect: its bits, apart.
effectSpellings : List Effect -> String
effectSpellings [] = "none"
effectSpellings es = separated ", " (map effectSpelling es)

namespace Permission
  ||| what a value owns
  public export
  data Permission = Plain | Borrow | Own | Excl

export
Prelude.EqOrd.Eq Permission where
  Permission.Plain == Permission.Plain = True
  Permission.Borrow == Permission.Borrow = True
  Permission.Own == Permission.Own = True
  Permission.Excl == Permission.Excl = True
  _ == _ = False

-- How the syntax below spells each Permission.
permissionSpelling : Permission -> String
permissionSpelling Permission.Plain = "plain"
permissionSpelling Permission.Borrow = "borrow"
permissionSpelling Permission.Own = "own"
permissionSpelling Permission.Excl = "excl"

namespace Quantity
  ||| the number of uses Idris proved of a value
  public export
  data Quantity = Zero | One | Many

export
Prelude.EqOrd.Eq Quantity where
  Quantity.Zero == Quantity.Zero = True
  Quantity.One == Quantity.One = True
  Quantity.Many == Quantity.Many = True
  _ == _ = False

-- How the syntax below spells each Quantity.
quantitySpelling : Quantity -> String
quantitySpelling Quantity.Zero = "zero"
quantitySpelling Quantity.One = "one"
quantitySpelling Quantity.Many = "many"

------------------------------------------------------------------------------
-- Types
------------------------------------------------------------------------------

||| The idr dialect's types, one constructor each, named
||| after its C++ class; `ty` is the type of the types they hold.
public export
data IdrType : (ty : Type) -> Type where
  ||| `!idr.big`: an Integer
  BigType : IdrType ty
  ||| `!idr.box`: a value of the boxed type declared by idr.data ... box
  BoxType : (name : String) -> IdrType ty
  ||| `!idr.data`: a value of the unboxed sum declared by idr.data
  DataType : (name : String) -> IdrType ty
  ||| `!idr.dest`: a field of a cell built without it, to be written exactly once
  DestType : (value : ty) -> IdrType ty
  ||| `!idr.fn`: a closure
  FnType : (functionType : Signature ty) -> IdrType ty
  ||| `!idr.lazy`: a suspension of one value, forced once into this cell
  LazyType : (value : ty) -> IdrType ty
  ||| `!idr.nat`: a natural number: a non-negative big
  NatType : IdrType ty
  ||| `!idr.q`: a value at a grade: its quantity and what it owns
  QType : (quantity : Quantity) -> (permission : Permission) -> (value : ty) -> IdrType ty
  ||| `!idr.str`: a string (UTF-8)
  StrType : IdrType ty
  ||| `!idr.token`: the memory of a cell whose fields idr.take moved out, or null
  TokenType : IdrType ty
  ||| `!idr.world_carrier`: the IO world token
  WorldType : IdrType ty

||| The mnemonics of the idr dialect's types.
export
idrTypeMnemonics : List String
idrTypeMnemonics = ["big", "box", "data", "dest", "fn", "lazy", "nat", "q", "str", "token", "world_carrier"]

||| The mnemonic of each of the idr dialect's types.
export
idrTypeMnemonic : IdrType ty -> String
idrTypeMnemonic BigType = "big"
idrTypeMnemonic (BoxType _) = "box"
idrTypeMnemonic (DataType _) = "data"
idrTypeMnemonic (DestType _) = "dest"
idrTypeMnemonic (FnType _) = "fn"
idrTypeMnemonic (LazyType _) = "lazy"
idrTypeMnemonic NatType = "nat"
idrTypeMnemonic (QType _ _ _) = "q"
idrTypeMnemonic StrType = "str"
idrTypeMnemonic TokenType = "token"
idrTypeMnemonic WorldType = "world_carrier"

||| The text of each of the idr dialect's types, the types it
||| holds written by `t`.
export
idrTypeText : (t : ty -> String) -> IdrType ty -> String
idrTypeText t BigType = "!idr.big"
idrTypeText t (BoxType name) = fastConcat ["!idr.box<", (symbol name), ">"]
idrTypeText t (DataType name) = fastConcat ["!idr.data<", (symbol name), ">"]
idrTypeText t (DestType value) = fastConcat ["!idr.dest<", (t value), ">"]
idrTypeText t (FnType functionType) = fastConcat ["!idr.fn<", (signature t functionType), ">"]
idrTypeText t (LazyType value) = fastConcat ["!idr.lazy<", (t value), ">"]
idrTypeText t NatType = "!idr.nat"
idrTypeText t (QType quantity permission value) = fastConcat ["!idr.q<", (quantitySpelling quantity), ", ", (permissionSpelling permission), ", ", (t value), ">"]
idrTypeText t StrType = "!idr.str"
idrTypeText t TokenType = "!idr.token"
idrTypeText t WorldType = "!idr.world_carrier"

------------------------------------------------------------------------------
-- Attributes
------------------------------------------------------------------------------

||| The idr dialect's attributes, one constructor each, named
||| after its C++ class; `ty` is the type of the types they hold, `at` of the
||| attributes.
public export
data IdrAttr : (ty : Type) -> (at : Type) -> Type where
  ||| `#idr.big`: an integer of any size, in canonical decimal
  BigAttr : (value : String) -> IdrAttr ty at
  ||| `#idr.clone`: a clone, named, and the key it is the function of
  CloneAttr : (function : String) -> (key : at) -> IdrAttr ty at
  ||| `#idr.closure`: a closure of a function with its captures as attributes
  ClosureAttr : (callee : String) -> (captures : List at) -> IdrAttr ty at
  ||| `#idr.con`: a constructor of a sum or box, its fields as attributes, a list's cells flat
  ConAttr : (ctor : SymbolRef) -> (cells : List (List at)) -> (tail : Maybe at) -> (spine : Nat) -> IdrAttr ty at
  ||| `#idr.effects`: what a call of a function may do
  EffectAttr : (value : List Effect) -> IdrAttr ty at
  ||| `#idr.erased`: the erased value
  ErasedAttr : IdrAttr ty at
  ||| `#idr.key_apply`: the key of a clone that applies its callee's result
  KeyApplyAttr : (callee : String) -> (arity : Nat) -> IdrAttr ty at
  ||| `#idr.key_apply_field`: the key of a clone that applies field `index` of `ctor` of its callee's result
  KeyApplyFieldAttr : (callee : String) -> (arity : Nat) -> (ctor : String) -> (index : Nat) -> IdrAttr ty at
  ||| `#idr.key_closure`: a closure of `callee` in a key, over the patterns of its captures
  KeyClosureAttr : (callee : String) -> (captures : List at) -> IdrAttr ty at
  ||| `#idr.key_con`: a constructor `@data::@ctor` in a key, over the patterns of its fields
  KeyConAttr : (data' : String) -> (ctor : String) -> (fields : List at) -> IdrAttr ty at
  ||| `#idr.key_hole`: a runtime leaf of a key: the clone's parameter that holds it
  KeyHoleAttr : (index : Nat) -> IdrAttr ty at
  ||| `#idr.spec_key`: the key of a clone that specializes
  SpecKeyAttr : (origin : String) -> (patterns : List at) -> IdrAttr ty at

||| The mnemonics of the idr dialect's attributes.
export
idrAttrMnemonics : List String
idrAttrMnemonics = ["big", "clone", "closure", "con", "effects", "erased", "key_apply", "key_apply_field", "key_closure", "key_con", "key_hole", "spec_key"]

||| The mnemonic of each of the idr dialect's attributes.
export
idrAttrMnemonic : IdrAttr ty at -> String
idrAttrMnemonic (BigAttr _) = "big"
idrAttrMnemonic (CloneAttr _ _) = "clone"
idrAttrMnemonic (ClosureAttr _ _) = "closure"
idrAttrMnemonic (ConAttr _ _ _ _) = "con"
idrAttrMnemonic (EffectAttr _) = "effects"
idrAttrMnemonic ErasedAttr = "erased"
idrAttrMnemonic (KeyApplyAttr _ _) = "key_apply"
idrAttrMnemonic (KeyApplyFieldAttr _ _ _ _) = "key_apply_field"
idrAttrMnemonic (KeyClosureAttr _ _) = "key_closure"
idrAttrMnemonic (KeyConAttr _ _ _) = "key_con"
idrAttrMnemonic (KeyHoleAttr _) = "key_hole"
idrAttrMnemonic (SpecKeyAttr _ _) = "spec_key"

||| The text of each of the idr dialect's attributes, the types it
||| holds written by `t`, the attributes by `a`.
export
idrAttrText : (t : ty -> String) -> (a : at -> String) -> IdrAttr ty at -> String
idrAttrText t a (BigAttr value) = fastConcat ["#idr.big<", (utf8 value), ">"]
idrAttrText t a (CloneAttr function key) = fastConcat ["#idr.clone<", (symbol function), ", ", (a key), ">"]
idrAttrText t a (ClosureAttr callee captures) = fastConcat ["#idr.closure<", (symbol callee), ", ", (array a captures), ">"]
idrAttrText t a (ConAttr ctor cells tail spine) = fastConcat ["#idr.con<", (symbolRef ctor), ", ", (commaSeparated (map (\v => array a v) cells)), maybe "" (\tail => fastConcat [" tail ", (a tail)]) tail, " along ", (show spine), ">"]
idrAttrText t a (EffectAttr value) = fastConcat ["#idr.effects<", (effectSpellings value), ">"]
idrAttrText t a ErasedAttr = "#idr.erased"
idrAttrText t a (KeyApplyAttr callee arity) = fastConcat ["#idr.key_apply<", (utf8 callee), ", ", (show arity), ">"]
idrAttrText t a (KeyApplyFieldAttr callee arity ctor index) = fastConcat ["#idr.key_apply_field<", (utf8 callee), ", ", (show arity), ", ", (utf8 ctor), ", ", (show index), ">"]
idrAttrText t a (KeyClosureAttr callee captures) = fastConcat ["#idr.key_closure<", (utf8 callee), ", ", (array a captures), ">"]
idrAttrText t a (KeyConAttr data' ctor fields) = fastConcat ["#idr.key_con<", (utf8 data'), ", ", (utf8 ctor), ", ", (array a fields), ">"]
idrAttrText t a (KeyHoleAttr index) = fastConcat ["#idr.key_hole<", (show index), ">"]
idrAttrText t a (SpecKeyAttr origin patterns) = fastConcat ["#idr.spec_key<", (utf8 origin), ", ", (array a patterns), ">"]

