||| The math dialect's syntax, as the Idris side writes it: the enums
||| its ops, types and attributes take, and its types and attributes, which
||| IdrisMLIR.MLIR's types and attributes hold. Generated by idris-mlir-tblgen
||| -gen-idris-syntax from the dialect's ODS; `make build` writes it
||| (tools/dialects.sh). Do not edit.
module IdrisMLIR.Syntax.Math

import IdrisMLIR.MLIR.Text

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace RoundingMode
  ||| Floating point rounding mode
  public export
  data RoundingMode = ToNearestEven | Downward | Upward | TowardZero | ToNearestAway

export
Prelude.EqOrd.Eq RoundingMode where
  RoundingMode.ToNearestEven == RoundingMode.ToNearestEven = True
  RoundingMode.Downward == RoundingMode.Downward = True
  RoundingMode.Upward == RoundingMode.Upward = True
  RoundingMode.TowardZero == RoundingMode.TowardZero = True
  RoundingMode.ToNearestAway == RoundingMode.ToNearestAway = True
  _ == _ = False

