||| The memref dialect's syntax, as the Idris side writes it: the enums
||| its ops, types and attributes take, and its types and attributes, which
||| IdrisMLIR.MLIR's types and attributes hold. Generated by idris-mlir-tblgen
||| -gen-idris-syntax from the dialect's ODS; `make build` writes it
||| (tools/dialects.sh). Do not edit.
module IdrisMLIR.Syntax.MemRef

import IdrisMLIR.MLIR.Text

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace AtomicRMWKind
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  public export
  data AtomicRMWKind = Addf | Addi | Andi | Assign | Maximumf | Maxnumf | Maxs | Maxu | Minimumf | Minnumf | Mins | Minu | Mulf | Muli | Ori | Xori

export
Prelude.EqOrd.Eq AtomicRMWKind where
  AtomicRMWKind.Addf == AtomicRMWKind.Addf = True
  AtomicRMWKind.Addi == AtomicRMWKind.Addi = True
  AtomicRMWKind.Andi == AtomicRMWKind.Andi = True
  AtomicRMWKind.Assign == AtomicRMWKind.Assign = True
  AtomicRMWKind.Maximumf == AtomicRMWKind.Maximumf = True
  AtomicRMWKind.Maxnumf == AtomicRMWKind.Maxnumf = True
  AtomicRMWKind.Maxs == AtomicRMWKind.Maxs = True
  AtomicRMWKind.Maxu == AtomicRMWKind.Maxu = True
  AtomicRMWKind.Minimumf == AtomicRMWKind.Minimumf = True
  AtomicRMWKind.Minnumf == AtomicRMWKind.Minnumf = True
  AtomicRMWKind.Mins == AtomicRMWKind.Mins = True
  AtomicRMWKind.Minu == AtomicRMWKind.Minu = True
  AtomicRMWKind.Mulf == AtomicRMWKind.Mulf = True
  AtomicRMWKind.Muli == AtomicRMWKind.Muli = True
  AtomicRMWKind.Ori == AtomicRMWKind.Ori = True
  AtomicRMWKind.Xori == AtomicRMWKind.Xori = True
  _ == _ = False

