||| The ub dialect's syntax, as the Idris side writes it: the enums
||| its ops, types and attributes take, and its types and attributes, which
||| IdrisMLIR.MLIR's types and attributes hold. Generated by idris-mlir-tblgen
||| -gen-idris-syntax from the dialect's ODS; `make build` writes it
||| (tools/dialects.sh). Do not edit.
module IdrisMLIR.Syntax.UB

import IdrisMLIR.MLIR.Text

%default total

------------------------------------------------------------------------------
-- Attributes
------------------------------------------------------------------------------

||| The ub dialect's attributes, one constructor each, named
||| after its C++ class; `ty` is the type of the types they hold, `at` of the
||| attributes.
public export
data UBAttr : (ty : Type) -> (at : Type) -> Type where
  ||| `#ub.poison`
  PoisonAttr : UBAttr ty at

||| The mnemonics of the ub dialect's attributes.
export
ubAttrMnemonics : List String
ubAttrMnemonics = ["poison"]

||| The mnemonic of each of the ub dialect's attributes.
export
ubAttrMnemonic : UBAttr ty at -> String
ubAttrMnemonic PoisonAttr = "poison"

||| The text of each of the ub dialect's attributes, the types it
||| holds written by `t`, the attributes by `a`.
export
ubAttrText : (t : ty -> String) -> (a : at -> String) -> UBAttr ty at -> String
ubAttrText t a PoisonAttr = "#ub.poison"

