#!/bin/sh
# Assembles one self-contained dispatch per lane from parts/: the lane's
# body, the common obligations and the six binding rules, verbatim, so the
# shared text cannot drift between lanes.
# Run: sh proposals/0002-representation-cutover/dispatch/assemble.sh
set -eu
here=$(cd "$(dirname "$0")" && pwd)
parts=$here/parts
count=0
for part in "$parts"/U[0-9][0-9]-*.md; do
  name=$(basename "$part")
  {
    printf '<!-- Generated by dispatch/assemble.sh from parts/%s; edit the part, not this file. -->\n' "$name"
    cat "$part"
    printf '\n'
    cat "$parts/common-obligations.md"
    printf '\n'
    cat "$parts/binding-rules.md"
  } > "$here/$name"
  count=$((count + 1))
done
echo "assembled $count dispatches"
