#loc4 = loc("tests/idr/rc/live.mlir":14:3)
#loc5 = loc("tests/idr/rc/live.mlir":14:28)
#loc14 = loc("tests/idr/rc/live.mlir":30:3)
#loc15 = loc("tests/idr/rc/live.mlir":30:26)
#loc18 = loc("tests/idr/rc/live.mlir":36:13)
#loc19 = loc("tests/idr/rc/live.mlir":36:22)
#loc26 = loc("tests/idr/rc/live.mlir":45:26)
#loc27 = loc("tests/idr/rc/live.mlir":45:44)
#loc30 = loc("tests/idr/rc/live.mlir":50:13)
#loc31 = loc("tests/idr/rc/live.mlir":50:22)
#loc47 = loc("tests/idr/rc/live.mlir":79:10)
#loc49 = loc("tests/idr/rc/live.mlir":64:13)
#loc50 = loc("tests/idr/rc/live.mlir":64:22)
#loc54 = loc("tests/idr/rc/live.mlir":83:11)
#loc60 = loc(callsite(#loc49 at #loc47))
#loc61 = loc(callsite(#loc50 at #loc47))
#loc65 = loc(callsite(#loc49 at #loc54))
#loc66 = loc(callsite(#loc50 at #loc54))
module attributes {dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, f80 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i8 = dense<8> : vector<2xi64>, i16 = dense<16> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 8, 16, 32, 64>, "dlti.stack_alignment" = 128 : i64>, idr.program, idr.stage = "owned", llvm.target = #llvm.target<triple = "x86_64-unknown-linux-musl", chip = "x86-64-v3", features = <["+64bit", "+64bit-mode", "+allow-light-256-bit", "+avx", "+avx2", "+bmi", "+bmi2", "+cmov", "+crc32", "+cx16", "+cx8", "+f16c", "+false-deps-lzcnt", "+false-deps-popcnt", "+false-deps-tzcnt", "+fast-15bytenop", "+fast-scalar-fsqrt", "+fast-shld-rotate", "+fast-variable-crosslane-shuffle", "+fast-variable-perlane-shuffle", "+fma", "+fxsr", "+idivq-to-divl", "+lzcnt", "+macrofusion", "+mmx", "+movbe", "+nopl", "+popcnt", "+sahf", "+slow-3ops-lea", "+sse", "+sse2", "+sse3", "+sse4.1", "+sse4.2", "+ssse3", "+vzeroupper", "+x87", "+xsave"]>>} {
  idr.data @L box {
    idr.ctor @N () loc(#loc2)
    idr.ctor @C (i64, !idr.box<@L>) loc(#loc3)
  } loc(#loc1)
  func.func private @build(%arg0: i64 loc("tests/idr/rc/live.mlir":14:28)) -> !idr.own<!idr.box<@L>> attributes {idr.effects = #idr.effects<none>, no_inline} {
    %c1_i64 = arith.constant 1 : i64 loc(#loc6)
    %0 = idr.constant #idr.con<@L::@N, []> : !idr.box<@L> loc(#loc6)
    %1 = idr.match_lit %arg0 : i64 -> (!idr.own<!idr.box<@L>>) {
    case 0 {
      %2 = idr.dup %0 : !idr.box<@L> loc(#loc8)
      idr.yield %2 : !idr.own<!idr.box<@L>> loc(#loc8)
    }
    default {
      %2 = arith.subi %arg0, %c1_i64 : i64 loc(#loc9)
      %3 = idr.dest.pending : !idr.own<!idr.box<@L>> loc(#loc10)
      %4 = idr.con @L::@C(%arg0, %3) : (i64, !idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc11)
      %5 = idr.borrow %4 : !idr.own<!idr.box<@L>> loc(#loc10)
      %6 = idr.dest.of %5[@C, 1] : <@L> -> <!idr.box<@L>> loc(#loc10)
      func.call @build$trmc(%2, %6) : (i64, !idr.dest<!idr.box<@L>>) -> () loc(#loc10)
      idr.yield %4 : !idr.own<!idr.box<@L>> loc(#loc12)
    }
    } loc(#loc7)
    return %1 : !idr.own<!idr.box<@L>> loc(#loc13)
  } loc(#loc4)
  func.func private @build$trmc(%arg0: i64 loc("tests/idr/rc/live.mlir":14:28), %arg1: !idr.dest<!idr.box<@L>> loc("tests/idr/rc/live.mlir":14:3)) attributes {idr.effects = #idr.effects<none>, no_inline} {
    %c1_i64 = arith.constant 1 : i64 loc(#loc6)
    %0 = idr.constant #idr.con<@L::@N, []> : !idr.box<@L> loc(#loc6)
    idr.match_lit %arg0 : i64 -> () {
    case 0 {
      %1 = idr.dup %0 : !idr.box<@L> loc(#loc8)
      idr.dest.write %arg1, %1 : <!idr.box<@L>> loc(#loc8)
      idr.yield loc(#loc8)
    }
    default {
      %1 = arith.subi %arg0, %c1_i64 : i64 loc(#loc9)
      %2 = idr.dest.pending : !idr.own<!idr.box<@L>> loc(#loc10)
      %3 = idr.con @L::@C(%arg0, %2) : (i64, !idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc11)
      %4 = idr.borrow %3 : !idr.own<!idr.box<@L>> loc(#loc10)
      %5 = idr.dest.of %4[@C, 1] : <@L> -> <!idr.box<@L>> loc(#loc10)
      idr.dest.write %arg1, %3 : <!idr.box<@L>> loc(#loc10)
      func.call @build$trmc(%1, %5) : (i64, !idr.dest<!idr.box<@L>>) -> () loc(#loc10)
      idr.yield loc(#loc12)
    }
    } loc(#loc7)
    return loc(#loc13)
  } loc(#loc4)
  func.func private @map(%arg0: !idr.own<!idr.box<@L>> loc("tests/idr/rc/live.mlir":30:26)) -> !idr.own<!idr.box<@L>> attributes {idr.effects = #idr.effects<none>, no_inline} {
    %0 = idr.constant #idr.con<@L::@N, []> : !idr.box<@L> loc(#loc6)
    %1 = idr.borrow %arg0 : !idr.own<!idr.box<@L>> loc(#loc16)
    %2 = idr.match %1 : !idr.box<@L> -> (!idr.own<!idr.box<@L>>) {
    case @N() {
      %3 = idr.take %arg0 @L::@N : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>) loc(#loc16)
      %4 = idr.dup %0 : !idr.box<@L> loc(#loc17)
      idr.drop %3 : !idr.own<!idr.token> loc(#loc17)
      idr.yield %4 : !idr.own<!idr.box<@L>> loc(#loc17)
    }
    case @C(%arg1: i64 loc("tests/idr/rc/live.mlir":36:13), %arg2: !idr.box<@L> loc("tests/idr/rc/live.mlir":36:22)) {
      %3:3 = idr.take %arg0 @L::@C : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>, i64, !idr.own<!idr.box<@L>>) loc(#loc16)
      %4 = arith.muli %3#1, %3#1 : i64 loc(#loc20)
      %5 = idr.dest.pending : !idr.own<!idr.box<@L>> loc(#loc21)
      %6 = idr.reuse %3#0 @L::@C(%4, %5) : (i64, !idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc22)
      %7 = idr.borrow %6 : !idr.own<!idr.box<@L>> loc(#loc21)
      %8 = idr.dest.of %7[@C, 1] : <@L> -> <!idr.box<@L>> loc(#loc21)
      func.call @map$trmc(%3#2, %8) : (!idr.own<!idr.box<@L>>, !idr.dest<!idr.box<@L>>) -> () loc(#loc21)
      idr.yield %6 : !idr.own<!idr.box<@L>> loc(#loc23)
    }
    } loc(#loc16)
    return %2 : !idr.own<!idr.box<@L>> loc(#loc24)
  } loc(#loc14)
  func.func private @map$trmc(%arg0: !idr.own<!idr.box<@L>> loc("tests/idr/rc/live.mlir":30:26), %arg1: !idr.dest<!idr.box<@L>> loc("tests/idr/rc/live.mlir":30:3)) attributes {idr.effects = #idr.effects<none>, no_inline} {
    %0 = idr.constant #idr.con<@L::@N, []> : !idr.box<@L> loc(#loc6)
    %1 = idr.borrow %arg0 : !idr.own<!idr.box<@L>> loc(#loc16)
    idr.match %1 : !idr.box<@L> -> () {
    case @N() {
      %2 = idr.take %arg0 @L::@N : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>) loc(#loc16)
      %3 = idr.dup %0 : !idr.box<@L> loc(#loc17)
      idr.drop %2 : !idr.own<!idr.token> loc(#loc17)
      idr.dest.write %arg1, %3 : <!idr.box<@L>> loc(#loc17)
      idr.yield loc(#loc17)
    }
    case @C(%arg2: i64 loc("tests/idr/rc/live.mlir":36:13), %arg3: !idr.box<@L> loc("tests/idr/rc/live.mlir":36:22)) {
      %2:3 = idr.take %arg0 @L::@C : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>, i64, !idr.own<!idr.box<@L>>) loc(#loc16)
      %3 = arith.muli %2#1, %2#1 : i64 loc(#loc20)
      %4 = idr.dest.pending : !idr.own<!idr.box<@L>> loc(#loc21)
      %5 = idr.reuse %2#0 @L::@C(%3, %4) : (i64, !idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc22)
      %6 = idr.borrow %5 : !idr.own<!idr.box<@L>> loc(#loc21)
      %7 = idr.dest.of %6[@C, 1] : <@L> -> <!idr.box<@L>> loc(#loc21)
      idr.dest.write %arg1, %5 : <!idr.box<@L>> loc(#loc21)
      func.call @map$trmc(%2#2, %7) : (!idr.own<!idr.box<@L>>, !idr.dest<!idr.box<@L>>) -> () loc(#loc21)
      idr.yield loc(#loc23)
    }
    } loc(#loc16)
    return loc(#loc24)
  } loc(#loc14)
  func.func private @sum(%arg0: !idr.box<@L> loc("tests/idr/rc/live.mlir":45:26), %arg1: i64 loc("tests/idr/rc/live.mlir":45:44)) -> i64 attributes {idr.effects = #idr.effects<none>, no_inline} {
    %0 = idr.match %arg0 : !idr.box<@L> -> (i64) {
    case @N() {
      idr.yield %arg1 : i64 loc(#loc29)
    }
    case @C(%arg2: i64 loc("tests/idr/rc/live.mlir":50:13), %arg3: !idr.box<@L> loc("tests/idr/rc/live.mlir":50:22)) {
      %1 = arith.addi %arg1, %arg2 : i64 loc(#loc32)
      %2 = func.call @sum(%arg3, %1) : (!idr.box<@L>, i64) -> i64 loc(#loc33)
      idr.yield %2 : i64 loc(#loc34)
    }
    } loc(#loc28)
    return %0 : i64 loc(#loc35)
  } loc(#loc25)
  func.func @Prog.main() -> i64 attributes {idr.effects = #idr.effects<none>} {
    %c256_i64 = arith.constant 256 : i64 loc(#loc6)
    %c0_i64 = arith.constant 0 : i64 loc(#loc6)
    %c10_i64 = arith.constant 10 : i64 loc(#loc6)
    %c3_i64 = arith.constant 3 : i64 loc(#loc6)
    %0 = call @build(%c10_i64) : (i64) -> !idr.own<!idr.box<@L>> loc(#loc37)
    %1 = call @map(%0) : (!idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc38)
    %2 = idr.borrow %1 : !idr.own<!idr.box<@L>> loc(#loc39)
    %3 = call @sum(%2, %c0_i64) : (!idr.box<@L>, i64) -> i64 loc(#loc39)
    %4 = call @map(%1) : (!idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc40)
    %5 = idr.borrow %4 : !idr.own<!idr.box<@L>> loc(#loc41)
    %6 = call @sum(%5, %c0_i64) : (!idr.box<@L>, i64) -> i64 loc(#loc41)
    %7 = call @build(%c3_i64) : (i64) -> !idr.own<!idr.box<@L>> loc(#loc42)
    %8 = idr.borrow %7 : !idr.own<!idr.box<@L>> loc(#loc43)
    %9 = idr.dup %8 : !idr.box<@L> loc(#loc43)
    %10 = call @map(%9) : (!idr.own<!idr.box<@L>>) -> !idr.own<!idr.box<@L>> loc(#loc43)
    %11 = idr.borrow %7 : !idr.own<!idr.box<@L>> loc(#loc44)
    %12 = call @sum(%11, %c0_i64) : (!idr.box<@L>, i64) -> i64 loc(#loc44)
    idr.drop %7 : !idr.own<!idr.box<@L>> loc(#loc45)
    %13 = arith.addi %3, %6 : i64 loc(#loc45)
    %14 = idr.borrow %4 : !idr.own<!idr.box<@L>> loc(#loc58)
    %15 = idr.match %14 : !idr.box<@L> -> (i64) {
    case @N() {
      %20 = idr.take %4 @L::@N : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>) loc(#loc58)
      idr.drop %20 : !idr.own<!idr.token> loc(#loc59)
      idr.yield %13 : i64 loc(#loc59)
    }
    case @C(%arg0: i64 loc(callsite(#loc49 at #loc47)), %arg1: !idr.box<@L> loc(callsite(#loc50 at #loc47))) {
      %20:3 = idr.take %4 @L::@C : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>, i64, !idr.own<!idr.box<@L>>) loc(#loc58)
      idr.drop %20#0 : !idr.own<!idr.token> loc(#loc51)
      idr.drop %20#2 : !idr.own<!idr.box<@L>> loc(#loc51)
      %21 = arith.addi %13, %20#1 : i64 loc(#loc51)
      idr.yield %21 : i64 loc(#loc62)
    }
    } loc(#loc58)
    %16 = arith.addi %15, %12 : i64 loc(#loc53)
    %17 = idr.borrow %10 : !idr.own<!idr.box<@L>> loc(#loc63)
    %18 = idr.match %17 : !idr.box<@L> -> (i64) {
    case @N() {
      %20 = idr.take %10 @L::@N : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>) loc(#loc63)
      idr.drop %20 : !idr.own<!idr.token> loc(#loc64)
      idr.yield %16 : i64 loc(#loc64)
    }
    case @C(%arg0: i64 loc(callsite(#loc49 at #loc54)), %arg1: !idr.box<@L> loc(callsite(#loc50 at #loc54))) {
      %20:3 = idr.take %10 @L::@C : !idr.own<!idr.box<@L>> -> (!idr.own<!idr.token>, i64, !idr.own<!idr.box<@L>>) loc(#loc63)
      idr.drop %20#0 : !idr.own<!idr.token> loc(#loc55)
      idr.drop %20#2 : !idr.own<!idr.box<@L>> loc(#loc55)
      %21 = arith.addi %16, %20#1 : i64 loc(#loc55)
      idr.yield %21 : i64 loc(#loc67)
    }
    } loc(#loc63)
    %19 = arith.remsi %18, %c256_i64 : i64 loc(#loc56)
    return %19 : i64 loc(#loc57)
  } loc(#loc36)
} loc(#loc)
#loc = loc("tests/idr/rc/live.mlir":9:1)
#loc1 = loc("tests/idr/rc/live.mlir":10:3)
#loc2 = loc("tests/idr/rc/live.mlir":11:5)
#loc3 = loc("tests/idr/rc/live.mlir":12:5)
#loc6 = loc(unknown)
#loc7 = loc("tests/idr/rc/live.mlir":15:10)
#loc8 = loc("tests/idr/rc/live.mlir":18:7)
#loc9 = loc("tests/idr/rc/live.mlir":22:12)
#loc10 = loc("tests/idr/rc/live.mlir":23:12)
#loc11 = loc("tests/idr/rc/live.mlir":24:12)
#loc12 = loc("tests/idr/rc/live.mlir":25:7)
#loc13 = loc("tests/idr/rc/live.mlir":28:5)
#loc16 = loc("tests/idr/rc/live.mlir":31:10)
#loc17 = loc("tests/idr/rc/live.mlir":34:7)
#loc20 = loc("tests/idr/rc/live.mlir":37:13)
#loc21 = loc("tests/idr/rc/live.mlir":38:13)
#loc22 = loc("tests/idr/rc/live.mlir":39:12)
#loc23 = loc("tests/idr/rc/live.mlir":40:7)
#loc24 = loc("tests/idr/rc/live.mlir":43:5)
#loc25 = loc("tests/idr/rc/live.mlir":45:3)
#loc28 = loc("tests/idr/rc/live.mlir":46:10)
#loc29 = loc("tests/idr/rc/live.mlir":48:7)
#loc32 = loc("tests/idr/rc/live.mlir":51:12)
#loc33 = loc("tests/idr/rc/live.mlir":52:12)
#loc34 = loc("tests/idr/rc/live.mlir":53:7)
#loc35 = loc("tests/idr/rc/live.mlir":56:5)
#loc36 = loc("tests/idr/rc/live.mlir":70:3)
#loc37 = loc("tests/idr/rc/live.mlir":74:10)
#loc38 = loc("tests/idr/rc/live.mlir":75:10)
#loc39 = loc("tests/idr/rc/live.mlir":76:11)
#loc40 = loc("tests/idr/rc/live.mlir":77:11)
#loc41 = loc("tests/idr/rc/live.mlir":78:11)
#loc42 = loc("tests/idr/rc/live.mlir":80:10)
#loc43 = loc("tests/idr/rc/live.mlir":81:10)
#loc44 = loc("tests/idr/rc/live.mlir":82:10)
#loc45 = loc("tests/idr/rc/live.mlir":84:11)
#loc46 = loc("tests/idr/rc/live.mlir":59:10)
#loc48 = loc("tests/idr/rc/live.mlir":62:7)
#loc51 = loc("tests/idr/rc/live.mlir":85:11)
#loc52 = loc("tests/idr/rc/live.mlir":65:7)
#loc53 = loc("tests/idr/rc/live.mlir":86:11)
#loc55 = loc("tests/idr/rc/live.mlir":87:11)
#loc56 = loc("tests/idr/rc/live.mlir":89:10)
#loc57 = loc("tests/idr/rc/live.mlir":90:5)
#loc58 = loc(callsite(#loc46 at #loc47))
#loc59 = loc(callsite(#loc48 at #loc47))
#loc62 = loc(callsite(#loc52 at #loc47))
#loc63 = loc(callsite(#loc46 at #loc54))
#loc64 = loc(callsite(#loc48 at #loc54))
#loc67 = loc(callsite(#loc52 at #loc54))
