# idris-mlir's commands. GNU make.
#
#   make bootstrap         build the pinned toolchain into .toolchain/ (tools/bootstrap.sh all)
#   make doctor            what the build needs, and what is built
#   make verify-pins       the Idris submodule is at its staged gitlink, unmodified
#   make check             tests/spec: the pins, the commands and the layout;
#                          always, without a build
#   make build             the C++ dev preset and the Idris compiler; after any code change
#   make test              tests/compiler, profile, e2e, determinism, registry and
#                          toolchain; after compiler changes
#   make test-idr          tests/idr, the idr dialect, with FileCheck; after C++ or
#                          contract changes
#   make test-mlir-tools   tests/upstream, the upstream bugs still reproduce with the
#                          pinned tools; after changing upstream MLIR usage
#   make compile SRC=Prog.idr OUT=prog
#   make bench             bench/run.sh; ARGS='--runs 3 fib' passes arguments
#
# The test commands run tests/Main.idr, a golden runner on Test.Golden. They
# take only='NAME...' and except='NAME...' (substrings of test paths such as
# e2e/v1/hello), threads=N (default: the number of CPUs),
# INTERACTIVE=--interactive (offer to accept new output) and time_scale=N
# (multiplies every timeout: each command a test runs gets 60 s
# and each test 300 s, or what its run script sets). Each ends with the
# number of tests that passed and the list of those that failed, and fails
# if any did.

ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
# Where the pinned tools are, from tools/toolchain.sh, which the scripts share.
toolchain = $(shell root='$(ROOT)'; . '$(ROOT)/tools/toolchain.sh'; printf '%s' "$$$(1)")
IDRIS_PREFIX := $(call toolchain,idris_prefix)
IDRIS2 := $(call toolchain,idris2)
CMAKE := $(call toolchain,cmake)
PINNED_CC := $(call toolchain,pinned_cc)
IDRIS_MLIR_CC := $(call toolchain,idris_mlir_cc)
COMPILER := $(ROOT)/compiler/build/exec/idris-mlir
PATHS_MODULE := $(ROOT)/compiler/src/IdrisMLIR/Frontend/Paths.idr
RUNNER := $(ROOT)/tests/build/exec/runtests
PINS := $(ROOT)/tools/verify-pins.sh

# Every command runs the pinned Idris, and no package path inherited from
# another installation. CHEZ is the Chez Scheme it was built with.
unexport IDRIS2_PATH IDRIS2_PACKAGE_PATH IDRIS2_INC_CGS IDRIS2_INC_SRC IDRIS2_DATA IDRIS2_LIBS IDRIS2_CG IDRIS2_BOOT
export IDRIS2_PREFIX := $(IDRIS_PREFIX)
export PATH := $(IDRIS_PREFIX)/bin:$(PATH)
export IDRIS_MLIR_ROOT := $(ROOT)
STAMPED_CHEZ := $(shell root='$(ROOT)'; . '$(ROOT)/tools/toolchain.sh'; stamp_field "$$idris_prefix" scheme)
ifneq ($(STAMPED_CHEZ),)
export CHEZ := $(STAMPED_CHEZ)
endif

threads ?= $(shell nproc 2> /dev/null || getconf _NPROCESSORS_ONLN 2> /dev/null || echo 1)
only ?=
except ?=
INTERACTIVE ?=
time_scale ?= 1
export IDRIS_MLIR_TIME_SCALE := $(time_scale)
GOLDEN = --threads $(threads) $(INTERACTIVE) --only '$(only)' --except '$(except)'

.PHONY: help bootstrap doctor verify-pins env check build paths test test-idr test-mlir-tools \
        runner compile bench
.DEFAULT_GOAL := help

# `make` alone lists the commands: the comment that starts this file.
help:
	@sed -n '/^#/!q; s/^# \{0,1\}//p' $(ROOT)/Makefile

bootstrap:
	$(ROOT)/tools/bootstrap.sh all

doctor:
	@$(ROOT)/tools/doctor.sh

verify-pins:
	@$(PINS)

# The environment the commands run in.
env:
	@env | grep -E '^(IDRIS2_[A-Z_]*|CHEZ|IDRIS_MLIR_ROOT)=' | sort

# The presets are the only interface for building C++.
build:
	@$(PINS) cmake ninja llvm sysroot
	cd $(ROOT) && $(CMAKE) --preset dev
	cd $(ROOT) && $(CMAKE) --build --preset dev
	@$(PINS) idris
	@$(MAKE) --no-print-directory paths
	cd $(ROOT)/compiler && $(IDRIS2) --build idris-mlir.ipkg

# The -o path runs the tools recorded here, never PATH.
paths:
	@{ printf '%s\n' \
	    '||| Generated by make build: the pinned tools the -o path runs.' \
	    '||| Do not edit.' \
	    'module IdrisMLIR.Frontend.Paths' '' \
	    'export' 'idrisMlirCc : String' 'idrisMlirCc = "$(IDRIS_MLIR_CC)"' '' \
	    'export' 'pinnedCc : String' 'pinnedCc = "$(PINNED_CC)"'; } > '$(PATHS_MODULE).new'
	@if cmp -s '$(PATHS_MODULE).new' '$(PATHS_MODULE)'; then \
	    rm '$(PATHS_MODULE).new'; else mv '$(PATHS_MODULE).new' '$(PATHS_MODULE)'; fi

runner:
	@$(PINS) idris
	cd $(ROOT)/tests && $(IDRIS2) --build tests.ipkg

check: runner
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite check $(GOLDEN)

test: runner
	@$(PINS) built llvm sysroot
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test $(GOLDEN)

test-idr: runner
	@$(PINS) built llvm test-tools sysroot
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test-idr $(GOLDEN)

test-mlir-tools: runner
	@$(PINS) llvm sysroot
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test-mlir-tools $(GOLDEN)

compile:
	@test -n '$(SRC)' && test -n '$(OUT)' || { echo 'usage: make compile SRC=Prog.idr OUT=prog' >&2; exit 2; }
	@$(PINS) built idris sysroot
	@$(ROOT)/tools/compile.sh '$(abspath $(SRC))' '$(abspath $(OUT))'

bench:
	@$(PINS) built idris sysroot
	$(ROOT)/bench/run.sh $(ARGS)
