# idris-mlir's commands (TEST-CMD-1, docs/architecture/14-testing.md). GNU make.
#
#   make bootstrap         build the pinned toolchain into .toolchain/ (tools/bootstrap.sh all)
#   make doctor            what the build needs, and what is built
#   make verify-pins       the Idris submodule is at its staged gitlink, unmodified
#   make check             tests/spec and tests/toolchain: repository rules; always
#   make build             the C++ dev preset and the Idris compiler; after any code change
#   make test              tests/compiler, profile, e2e, determinism, registry;
#                          after compiler changes
#   make test-idr          tests/idr, the idr dialect, with FileCheck; after C++ or
#                          contract changes
#   make test-mlir-tools   tests/mlir, the pinned upstream MLIR tools; after changing
#                          upstream MLIR usage
#   make compile SRC=Prog.idr OUT=prog
#   make bench             bench/run.sh; ARGS='--runs 3 fib' passes arguments
#   make ryu-tables        regenerate the Double printer's tables (LOW-DBL-2)
#
# The test commands run tests/Main.idr, a golden runner on Test.Golden. They
# take only='NAME...' and except='NAME...' (substrings of test paths such as
# e2e/v1/hello), threads=N (default: the number of CPUs) and
# INTERACTIVE=--interactive (offer to accept new output). Each ends with the
# number of tests that passed and the list of those that failed, and fails
# if any did.

ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
TOOLCHAIN := $(ROOT)/.toolchain
IDRIS_PREFIX := $(TOOLCHAIN)/idris2
IDRIS2 := $(IDRIS_PREFIX)/bin/idris2
CMAKE := $(TOOLCHAIN)/cmake/bin/cmake
PINNED_CC := $(TOOLCHAIN)/gcc/bin/gcc
COMPILER := $(ROOT)/compiler/build/exec/idris-mlir
IDRIS_MLIR_CC := $(ROOT)/build/dev/foreign/idr/idris-mlir-cc
PATHS_MODULE := $(ROOT)/compiler/src/IdrisMLIR/Frontend/Paths.idr
RUNNER := $(ROOT)/tests/build/exec/runtests
GEN_RYU_TABLES := $(ROOT)/tools/build/exec/gen-ryu-tables
RUNTIME := $(ROOT)/foreign/idr/lib/Lower/Runtime.mlir.inc
PINS := $(ROOT)/tools/verify-pins.sh

# Every command runs the pinned Idris, and no package path inherited from
# another installation (TC-PIN-2). CHEZ is the Chez Scheme it was built with.
unexport IDRIS2_PATH IDRIS2_PACKAGE_PATH IDRIS2_INC_CGS IDRIS2_DATA IDRIS2_LIBS IDRIS2_CG IDRIS2_BOOT
export IDRIS2_PREFIX := $(IDRIS_PREFIX)
export PATH := $(IDRIS_PREFIX)/bin:$(PATH)
export IDRIS_MLIR_ROOT := $(ROOT)
STAMPED_CHEZ := $(shell sed -n 's/.*"scheme"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' '$(IDRIS_PREFIX)/provenance.json' 2> /dev/null)
ifneq ($(STAMPED_CHEZ),)
export CHEZ := $(STAMPED_CHEZ)
endif

threads ?= $(shell nproc 2> /dev/null || getconf _NPROCESSORS_ONLN 2> /dev/null || echo 1)
only ?=
except ?=
INTERACTIVE ?=
GOLDEN = --threads $(threads) $(INTERACTIVE) --only '$(only)' --except '$(except)'

.PHONY: bootstrap doctor verify-pins env check build paths test test-idr test-mlir-tools \
        runner gen-ryu-tables ryu-tables compile bench

bootstrap:
	$(ROOT)/tools/bootstrap.sh all

doctor:
	@$(ROOT)/tools/doctor.sh

verify-pins:
	@$(PINS)

# The environment the commands run in.
env:
	@env | grep -E '^(IDRIS2_[A-Z_]*|CHEZ|IDRIS_MLIR_ROOT)=' | sort

# TC-CPP-2: the presets are the only interface for building C++.
build:
	@$(PINS) cmake llvm
	cd $(ROOT) && $(CMAKE) --preset dev
	cd $(ROOT) && $(CMAKE) --build --preset dev
	@$(PINS) idris gcc
	@$(MAKE) --no-print-directory paths
	cd $(ROOT)/compiler && $(IDRIS2) --build idris-mlir.ipkg

# DRV-FLOW-2: the -o path runs the tools recorded here, never PATH.
paths:
	@{ printf '%s\n' \
	    '||| Generated by make build: the pinned tools the -o path runs' \
	    '||| (DRV-FLOW-2). Do not edit.' \
	    'module IdrisMLIR.Frontend.Paths' '' \
	    'export' 'idrisMlirCc : String' 'idrisMlirCc = "$(IDRIS_MLIR_CC)"' '' \
	    'export' 'pinnedCc : String' 'pinnedCc = "$(PINNED_CC)"'; } > '$(PATHS_MODULE).new'
	@if cmp -s '$(PATHS_MODULE).new' '$(PATHS_MODULE)'; then \
	    rm '$(PATHS_MODULE).new'; else mv '$(PATHS_MODULE).new' '$(PATHS_MODULE)'; fi

runner:
	@$(PINS) idris
	cd $(ROOT)/tests && $(IDRIS2) --build tests.ipkg

gen-ryu-tables:
	@$(PINS) idris
	cd $(ROOT)/tools && $(IDRIS2) --build gen-ryu-tables.ipkg

ryu-tables: gen-ryu-tables
	$(GEN_RYU_TABLES) $(RUNTIME)

check: runner gen-ryu-tables
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite check $(GOLDEN)

test: runner
	@$(PINS) built llvm gcc
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test $(GOLDEN)

test-idr: runner
	@$(PINS) built llvm test-tools gcc
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test-idr $(GOLDEN)

test-mlir-tools: runner
	@$(PINS) llvm gcc
	cd $(ROOT)/tests && $(RUNNER) $(COMPILER) --suite test-mlir-tools $(GOLDEN)

compile:
	@test -n '$(SRC)' && test -n '$(OUT)' || { echo 'usage: make compile SRC=Prog.idr OUT=prog' >&2; exit 2; }
	@$(PINS) built idris gcc
	@$(ROOT)/tools/compile.sh '$(abspath $(SRC))' '$(abspath $(OUT))'

bench:
	@$(PINS) built idris gcc
	$(ROOT)/bench/run.sh $(ARGS)
