"""TEST-SEM-1: table-driven integer semantics over every integer type.

Each generated program is an ordinary v0 end-to-end fixture: `Prog.main` is 0
when every case agrees with the table, and otherwise the number of the first
case that disagrees. `Oracle.idr` proves `Prog.main = 0` with `Refl`, so the
stock evaluator agrees with the same table (SEM-REF-1). The table itself is
computed here from the rules in docs/architecture/03-semantics.md.

rule: TEST-SEM-1, SEM-INT-1, SEM-INT-2, SEM-INT-3, SEM-INT-5, SEM-INT-6, SEM-INT-7, PROF-PRIM-1
rule: LOW-DIV-1, IDR-DIV-1, IDR-DIV-2, IDR-IN-3, SEM-EVAL-1, SEM-EVAL-2
"""

from pathlib import Path
import tempfile

TYPES = {  # name: (width, signed)
    "Int": (64, True), "Int8": (8, True), "Int16": (16, True), "Int32": (32, True),
    "Int64": (64, True), "Bits8": (8, False), "Bits16": (16, False),
    "Bits32": (32, False), "Bits64": (64, False),
}
MAX_CASES = 120


def wrap(t, n):
    width, signed = TYPES[t]
    n %= 2 ** width
    return n - 2 ** width if signed and n >= 2 ** (width - 1) else n


def bounds(t):
    width, signed = TYPES[t]
    return (-(2 ** (width - 1)), 2 ** (width - 1) - 1) if signed else (0, 2 ** width - 1)


def values(t):
    lo, hi = bounds(t)
    if TYPES[t][1]:
        return [lo, lo + 1, -1, 0, 1, hi]
    return [0, 1, 2, 2 ** (TYPES[t][0] - 1), hi - 1, hi]


def div_values(t):
    lo, hi = bounds(t)
    if TYPES[t][1]:
        return [lo, -7, -2, -1, 0, 1, 2, 7, hi]
    return [0, 1, 2, 7, hi - 1, hi]


def euclid(a, b):
    q = abs(a) // abs(b)
    q = q if (a < 0) == (b < 0) else -q
    r = a - b * q
    if r < 0:
        return (q - 1, r + b) if b > 0 else (q + 1, r - b)
    return q, r


def div(t, a, b):
    return wrap(t, euclid(a, b)[0]) if TYPES[t][1] else a // b


def mod(t, a, b):
    return wrap(t, euclid(a, b)[1]) if TYPES[t][1] else a % b


def bits(t, op, a, b):
    width = TYPES[t][0]
    ua, ub = a % 2 ** width, b % 2 ** width
    return wrap(t, {"and": ua & ub, "or": ua | ub, "xor": ua ^ ub}[op])


COMPARE = {"lt": lambda a, b: a < b, "lte": lambda a, b: a <= b, "eq": lambda a, b: a == b,
           "gte": lambda a, b: a >= b, "gt": lambda a, b: a > b}


def lit(t, v):
    """An Idris expression of type t with value v, built from an Int literal."""
    as_int = wrap("Int", v)
    text = str(as_int) if as_int >= 0 else f"({as_int})"
    return text if t == "Int" else f"(prim__cast_Int{t} {text})"


def tables(t):
    """(title, [(expression, result type, expected value)])."""
    vs, ds = values(t), div_values(t)
    arith = [(f"(prim__{op}_{t} {lit(t, a)} {lit(t, b)})", t, wrap(t, f(a, b)))
             for op, f in (("add", lambda x, y: x + y), ("sub", lambda x, y: x - y),
                           ("mul", lambda x, y: x * y)) for a in vs for b in vs]
    divs = [(f"(prim__div_{t} {lit(t, a)} {lit(t, b)})", t, div(t, a, b)) for a in ds for b in ds if b != 0]
    mods = [(f"(prim__mod_{t} {lit(t, a)} {lit(t, b)})", t, mod(t, a, b)) for a in ds for b in ds if b != 0]
    bitw = [(f"(prim__{op}_{t} {lit(t, a)} {lit(t, b)})", t, bits(t, op, a, b))
            for op in ("and", "or", "xor") for a in vs for b in vs]
    cmp = [(f"(prim__{op}_{t} {lit(t, a)} {lit(t, b)})", "Int", int(COMPARE[op](a, b)))
           for op in COMPARE for a in vs for b in vs]
    casts = [(f"(prim__cast_{t}{u} {lit(t, a)})", u, wrap(u, a))
             for u in TYPES if u != t for a in vs]
    return [("arith", arith), ("div", divs), ("mod", mods), ("bitwise", bitw),
            ("compare", cmp), ("cast", casts)]


def program(cases):
    lines = ["module Prog", "",
             "-- Generated by tests/e2e/sem.py (TEST-SEM-1).", "",
             "public export", "chk : Int -> Int -> Int -> Int", "chk 1 _ rest = rest", "chk _ i _ = i", "",
             "public export partial", "main : Int", "main ="]
    body = "0"
    for i, (expr, ty, expected) in reversed(list(enumerate(cases, 1))):
        body = f"chk (prim__eq_{ty} {expr} {lit(ty, expected)}) {i}\n  ({body})"
    lines.append("  " + body)
    return "\n".join(lines) + "\n"


ORACLE = """module Oracle

import Builtin
import Prog

check : Prog.main = 0
check = Refl
"""


def cases(make_case):
    root = Path(tempfile.mkdtemp(prefix="idris-mlir-sem-"))
    found = []
    for t in TYPES:
        for title, table in tables(t):
            for part in range(0, len(table), MAX_CASES):
                chunk = table[part:part + MAX_CASES]
                name = f"SEM-INT-{t}-{title}-{part // MAX_CASES}"
                fixture = root / name
                fixture.mkdir()
                (fixture / "Prog.idr").write_text(program(chunk))
                (fixture / "Oracle.idr").write_text(ORACLE)
                found.append((f"e2e/v0/{name}", make_case(fixture)))
    return found
