||| Generated by tools/dev.py build: the pinned tools the -o path runs
||| (DRV-FLOW-2). Do not edit.
module IdrisMLIR.Frontend.Paths

export
idrisMlirCc : String
idrisMlirCc = "/tmp/claude-0/-home-user-idris-mlir/9e6c7b10-225a-5a6c-bf9d-31a304a4cdcc/scratchpad/idrscratch/build/idr/idris-mlir-cc"

export
pinnedCc : String
pinnedCc = "cc"
