// RUN: idris-mlir-opt %s -split-input-file -verify-diagnostics --idr-lower -o /dev/null
// RUN: awk 'BEGIN { print "idr.data @Many box {"; for (i = 0; i < 65537; i++) print "  idr.ctor @C" i " ()"; print "}"; print "func.func @Prog.main() -> i64 {"; print "  %z = arith.constant 0 : i64"; print "  return %z : i64"; print "}" }' > %t.many.mlir
// RUN: not idris-mlir-opt %t.many.mlir --idr-lower 2>&1 | FileCheck %s --check-prefix=MANY
// RUN: awk 'BEGIN { print "idr.data @Most box {"; for (i = 0; i < 65536; i++) print "  idr.ctor @C" i " ()"; print "}"; print "func.func @Prog.main() -> i64 {"; print "  %z = arith.constant 0 : i64"; print "  return %z : i64"; print "}" }' > %t.most.mlir
// RUN: idris-mlir-opt %t.most.mlir --idr-lower -o /dev/null
// A cell's header holds its tag in 16 bits and its number of object slots
// (counted references) in 8. What fits is lowered; what does not is
// rejected once, by name, where the layouts are decided, and never written
// as a header whose fields run into each other.
// MANY: unsupported (layout): the boxed type @Many has 65537 constructors, and a boxed type has at most 65536
// MANY-NOT: unsupported

// 255 counted references fit.
idr.data @Fits box {
  idr.ctor @A (!idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str)
}

// -----

idr.data @Wide box {
  // expected-error @+1 {{unsupported (layout): a cell of the constructor @A cannot be built: it holds 256 counted references}}
  idr.ctor @A (!idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str, !idr.str)
}

// -----

// An unboxed sum spreads over the cell that holds it: three counted slots
// in each of 86 fields are 258.
idr.data @Three {
  idr.ctor @P (!idr.str, !idr.str, !idr.str)
}
idr.data @Holder box {
  // expected-error @+1 {{it holds 258 counted references}}
  idr.ctor @H (!idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>, !idr.data<@Three>)
}
