||| The arith dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.Arith

import IdrisMLIR.MLIR

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace CmpFPredicate
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  public export
  data CmpFPredicate = AlwaysFalse | OEQ | OGT | OGE | OLT | OLE | ONE | ORD | UEQ | UGT | UGE | ULT | ULE | UNE | UNO | AlwaysTrue

-- The value that stands for a CmpFPredicate, as the ops below write it.
cmpFPredicateValue : CmpFPredicate -> Integer
cmpFPredicateValue CmpFPredicate.AlwaysFalse = 0
cmpFPredicateValue CmpFPredicate.OEQ = 1
cmpFPredicateValue CmpFPredicate.OGT = 2
cmpFPredicateValue CmpFPredicate.OGE = 3
cmpFPredicateValue CmpFPredicate.OLT = 4
cmpFPredicateValue CmpFPredicate.OLE = 5
cmpFPredicateValue CmpFPredicate.ONE = 6
cmpFPredicateValue CmpFPredicate.ORD = 7
cmpFPredicateValue CmpFPredicate.UEQ = 8
cmpFPredicateValue CmpFPredicate.UGT = 9
cmpFPredicateValue CmpFPredicate.UGE = 10
cmpFPredicateValue CmpFPredicate.ULT = 11
cmpFPredicateValue CmpFPredicate.ULE = 12
cmpFPredicateValue CmpFPredicate.UNE = 13
cmpFPredicateValue CmpFPredicate.UNO = 14
cmpFPredicateValue CmpFPredicate.AlwaysTrue = 15

namespace CmpIPredicate
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
  public export
  data CmpIPredicate = Eq | Ne | Slt | Sle | Sgt | Sge | Ult | Ule | Ugt | Uge

-- The value that stands for a CmpIPredicate, as the ops below write it.
cmpIPredicateValue : CmpIPredicate -> Integer
cmpIPredicateValue CmpIPredicate.Eq = 0
cmpIPredicateValue CmpIPredicate.Ne = 1
cmpIPredicateValue CmpIPredicate.Slt = 2
cmpIPredicateValue CmpIPredicate.Sle = 3
cmpIPredicateValue CmpIPredicate.Sgt = 4
cmpIPredicateValue CmpIPredicate.Sge = 5
cmpIPredicateValue CmpIPredicate.Ult = 6
cmpIPredicateValue CmpIPredicate.Ule = 7
cmpIPredicateValue CmpIPredicate.Ugt = 8
cmpIPredicateValue CmpIPredicate.Uge = 9

namespace RoundingMode
  ||| Floating point rounding mode
  public export
  data RoundingMode = ToNearestEven | Downward | Upward | TowardZero | ToNearestAway

-- The value that stands for a RoundingMode, as the ops below write it.
roundingModeValue : RoundingMode -> Integer
roundingModeValue RoundingMode.ToNearestEven = 0
roundingModeValue RoundingMode.Downward = 1
roundingModeValue RoundingMode.Upward = 2
roundingModeValue RoundingMode.TowardZero = 3
roundingModeValue RoundingMode.ToNearestAway = 4

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `arith.addf`: floating point addition operation
export
addfOp : {default Nothing fastmath : Maybe MlirAttr} -> {default Nothing roundingmode : Maybe RoundingMode} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
addfOp lhs rhs result =
  MkOp "arith.addf" [lhs, rhs] (attrIf "fastmath" id fastmath ++ attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode) [] [] [result]

||| `arith.addi`: integer addition operation
export
addiOp : {default Nothing overflowFlags : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
addiOp lhs rhs result =
  MkOp "arith.addi" [lhs, rhs] (attrIf "overflowFlags" id overflowFlags) [] [] [result]

||| `arith.addui_extended`: extended unsigned integer addition operation returning sum and overflow bit
export
adduiExtendedOp : (lhs : Value) -> (rhs : Value) -> (sum : MlirType) -> (overflow : MlirType) -> Op
adduiExtendedOp lhs rhs sum overflow =
  MkOp "arith.addui_extended" [lhs, rhs] [] [] [] [sum, overflow]

||| `arith.andi`: integer binary and
export
andiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
andiOp lhs rhs result =
  MkOp "arith.andi" [lhs, rhs] [] [] [] [result]

||| `arith.bitcast`: bitcast between values of equal bit width
export
bitcastOp : (in' : Value) -> (out : MlirType) -> Op
bitcastOp in' out =
  MkOp "arith.bitcast" [in'] [] [] [] [out]

||| `arith.ceildivsi`: signed ceil integer division operation
export
ceildivsiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
ceildivsiOp lhs rhs result =
  MkOp "arith.ceildivsi" [lhs, rhs] [] [] [] [result]

||| `arith.ceildivui`: unsigned ceil integer division operation
export
ceildivuiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
ceildivuiOp lhs rhs result =
  MkOp "arith.ceildivui" [lhs, rhs] [] [] [] [result]

||| `arith.cmpf`: floating-point comparison operation
export
cmpfOp : {default Nothing fastmath : Maybe MlirAttr} -> (predicate : CmpFPredicate) -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
cmpfOp predicate lhs rhs result =
  MkOp "arith.cmpf" [lhs, rhs] ([("predicate", integerAttr (cmpFPredicateValue predicate) (integerType 64))] ++ attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.cmpi`: integer comparison operation
export
cmpiOp : (predicate : CmpIPredicate) -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
cmpiOp predicate lhs rhs result =
  MkOp "arith.cmpi" [lhs, rhs] [("predicate", integerAttr (cmpIPredicateValue predicate) (integerType 64))] [] [] [result]

||| `arith.constant`: integer or floating point constant
export
constantOp : (value : MlirAttr) -> (result : MlirType) -> Op
constantOp value result =
  MkOp "arith.constant" [] [("value", value)] [] [] [result]

||| `arith.convertf`: cast between floating-point types of the same bitwidth
export
convertfOp : {default Nothing roundingmode : Maybe RoundingMode} -> {default Nothing fastmath : Maybe MlirAttr} -> (in' : Value) -> (out : MlirType) -> Op
convertfOp in' out =
  MkOp "arith.convertf" [in'] (attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode ++ attrIf "fastmath" id fastmath) [] [] [out]

||| `arith.divf`: floating point division operation
export
divfOp : {default Nothing fastmath : Maybe MlirAttr} -> {default Nothing roundingmode : Maybe RoundingMode} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
divfOp lhs rhs result =
  MkOp "arith.divf" [lhs, rhs] (attrIf "fastmath" id fastmath ++ attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode) [] [] [result]

||| `arith.divsi`: signed integer division operation
export
divsiOp : {default False isExact : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
divsiOp lhs rhs result =
  MkOp "arith.divsi" [lhs, rhs] (unitIf "isExact" isExact) [] [] [result]

||| `arith.divui`: unsigned integer division operation
export
divuiOp : {default False isExact : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
divuiOp lhs rhs result =
  MkOp "arith.divui" [lhs, rhs] (unitIf "isExact" isExact) [] [] [result]

||| `arith.extf`: cast from floating-point to wider floating-point
export
extfOp : {default Nothing fastmath : Maybe MlirAttr} -> (in' : Value) -> (out : MlirType) -> Op
extfOp in' out =
  MkOp "arith.extf" [in'] (attrIf "fastmath" id fastmath) [] [] [out]

||| `arith.extsi`: integer sign extension operation
export
extsiOp : (in' : Value) -> (out : MlirType) -> Op
extsiOp in' out =
  MkOp "arith.extsi" [in'] [] [] [] [out]

||| `arith.extui`: integer zero extension operation
export
extuiOp : {default False nonNeg : Bool} -> (in' : Value) -> (out : MlirType) -> Op
extuiOp in' out =
  MkOp "arith.extui" [in'] (unitIf "nonNeg" nonNeg) [] [] [out]

||| `arith.floordivsi`: signed floor integer division operation
export
floordivsiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
floordivsiOp lhs rhs result =
  MkOp "arith.floordivsi" [lhs, rhs] [] [] [] [result]

||| `arith.flush_denormals`: flush denormal floating-point values to zero
export
flushDenormalsOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
flushDenormalsOp operand result =
  MkOp "arith.flush_denormals" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.fptosi`: cast from floating-point type to integer type
export
fptosiOp : (in' : Value) -> (out : MlirType) -> Op
fptosiOp in' out =
  MkOp "arith.fptosi" [in'] [] [] [] [out]

||| `arith.fptoui`: cast from floating-point type to integer type
export
fptouiOp : (in' : Value) -> (out : MlirType) -> Op
fptouiOp in' out =
  MkOp "arith.fptoui" [in'] [] [] [] [out]

||| `arith.index_cast`: cast between index and integer types
export
indexCastOp : (in' : Value) -> (out : MlirType) -> Op
indexCastOp in' out =
  MkOp "arith.index_cast" [in'] [] [] [] [out]

||| `arith.index_castui`: unsigned cast between index and integer types
export
indexCastuiOp : {default False nonNeg : Bool} -> (in' : Value) -> (out : MlirType) -> Op
indexCastuiOp in' out =
  MkOp "arith.index_castui" [in'] (unitIf "nonNeg" nonNeg) [] [] [out]

||| `arith.maximumf`: floating-point maximum operation
export
maximumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
maximumfOp lhs rhs result =
  MkOp "arith.maximumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.maximumnumf`: floating-point maximumNumber operation
export
maximumnumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
maximumnumfOp lhs rhs result =
  MkOp "arith.maximumnumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.maxnumf`: floating-point maximum operation
export
maxnumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
maxnumfOp lhs rhs result =
  MkOp "arith.maxnumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.maxsi`: signed integer maximum operation
export
maxsiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
maxsiOp lhs rhs result =
  MkOp "arith.maxsi" [lhs, rhs] [] [] [] [result]

||| `arith.maxui`: unsigned integer maximum operation
export
maxuiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
maxuiOp lhs rhs result =
  MkOp "arith.maxui" [lhs, rhs] [] [] [] [result]

||| `arith.minimumf`: floating-point minimum operation
export
minimumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
minimumfOp lhs rhs result =
  MkOp "arith.minimumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.minimumnumf`: floating-point minimumNumber operation
export
minimumnumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
minimumnumfOp lhs rhs result =
  MkOp "arith.minimumnumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.minnumf`: floating-point minimum operation
export
minnumfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
minnumfOp lhs rhs result =
  MkOp "arith.minnumf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.minsi`: signed integer minimum operation
export
minsiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
minsiOp lhs rhs result =
  MkOp "arith.minsi" [lhs, rhs] [] [] [] [result]

||| `arith.minui`: unsigned integer minimum operation
export
minuiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
minuiOp lhs rhs result =
  MkOp "arith.minui" [lhs, rhs] [] [] [] [result]

||| `arith.mulf`: floating point multiplication operation
export
mulfOp : {default Nothing fastmath : Maybe MlirAttr} -> {default Nothing roundingmode : Maybe RoundingMode} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
mulfOp lhs rhs result =
  MkOp "arith.mulf" [lhs, rhs] (attrIf "fastmath" id fastmath ++ attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode) [] [] [result]

||| `arith.muli`: Integer multiplication operation.
export
muliOp : {default Nothing overflowFlags : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
muliOp lhs rhs result =
  MkOp "arith.muli" [lhs, rhs] (attrIf "overflowFlags" id overflowFlags) [] [] [result]

||| `arith.mulsi_extended`: extended signed integer multiplication operation
export
mulsiExtendedOp : (lhs : Value) -> (rhs : Value) -> (low : MlirType) -> (high : MlirType) -> Op
mulsiExtendedOp lhs rhs low high =
  MkOp "arith.mulsi_extended" [lhs, rhs] [] [] [] [low, high]

||| `arith.mului_extended`: extended unsigned integer multiplication operation
export
muluiExtendedOp : (lhs : Value) -> (rhs : Value) -> (low : MlirType) -> (high : MlirType) -> Op
muluiExtendedOp lhs rhs low high =
  MkOp "arith.mului_extended" [lhs, rhs] [] [] [] [low, high]

||| `arith.negf`: floating point negation
export
negfOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
negfOp operand result =
  MkOp "arith.negf" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.ori`: integer binary or
export
oriOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
oriOp lhs rhs result =
  MkOp "arith.ori" [lhs, rhs] [] [] [] [result]

||| `arith.remf`: floating point division remainder operation
export
remfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
remfOp lhs rhs result =
  MkOp "arith.remf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `arith.remsi`: signed integer division remainder operation
export
remsiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
remsiOp lhs rhs result =
  MkOp "arith.remsi" [lhs, rhs] [] [] [] [result]

||| `arith.remui`: unsigned integer division remainder operation
export
remuiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
remuiOp lhs rhs result =
  MkOp "arith.remui" [lhs, rhs] [] [] [] [result]

||| `arith.scaling_extf`: Upcasts input floats using provided scales values following OCP MXFP Spec
export
scalingExtfOp : {default Nothing fastmath : Maybe MlirAttr} -> (in' : Value) -> (scale : Value) -> (out : MlirType) -> Op
scalingExtfOp in' scale out =
  MkOp "arith.scaling_extf" [in', scale] (attrIf "fastmath" id fastmath) [] [] [out]

||| `arith.scaling_truncf`: Downcasts input floating point values using provided scales values following OCP MXFP Spec
export
scalingTruncfOp : {default Nothing roundingmode : Maybe RoundingMode} -> {default Nothing fastmath : Maybe MlirAttr} -> (in' : Value) -> (scale : Value) -> (out : MlirType) -> Op
scalingTruncfOp in' scale out =
  MkOp "arith.scaling_truncf" [in', scale] (attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode ++ attrIf "fastmath" id fastmath) [] [] [out]

||| `arith.select`: select operation
export
selectOp : (condition : Value) -> (trueValue : Value) -> (falseValue : Value) -> (result : MlirType) -> Op
selectOp condition trueValue falseValue result =
  MkOp "arith.select" [condition, trueValue, falseValue] [] [] [] [result]

||| `arith.shli`: integer left-shift
export
shliOp : {default Nothing overflowFlags : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
shliOp lhs rhs result =
  MkOp "arith.shli" [lhs, rhs] (attrIf "overflowFlags" id overflowFlags) [] [] [result]

||| `arith.shrsi`: signed integer right-shift
export
shrsiOp : {default False isExact : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
shrsiOp lhs rhs result =
  MkOp "arith.shrsi" [lhs, rhs] (unitIf "isExact" isExact) [] [] [result]

||| `arith.shrui`: unsigned integer right-shift
export
shruiOp : {default False isExact : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
shruiOp lhs rhs result =
  MkOp "arith.shrui" [lhs, rhs] (unitIf "isExact" isExact) [] [] [result]

||| `arith.sitofp`: cast from integer type to floating-point
export
sitofpOp : (in' : Value) -> (out : MlirType) -> Op
sitofpOp in' out =
  MkOp "arith.sitofp" [in'] [] [] [] [out]

||| `arith.subf`: floating point subtraction operation
export
subfOp : {default Nothing fastmath : Maybe MlirAttr} -> {default Nothing roundingmode : Maybe RoundingMode} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
subfOp lhs rhs result =
  MkOp "arith.subf" [lhs, rhs] (attrIf "fastmath" id fastmath ++ attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode) [] [] [result]

||| `arith.subi`: Integer subtraction operation.
export
subiOp : {default Nothing overflowFlags : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
subiOp lhs rhs result =
  MkOp "arith.subi" [lhs, rhs] (attrIf "overflowFlags" id overflowFlags) [] [] [result]

||| `arith.subui_extended`: extended unsigned integer subtraction operation returning difference and     borrow bit
export
subuiExtendedOp : (lhs : Value) -> (rhs : Value) -> (diff : MlirType) -> (borrow : MlirType) -> Op
subuiExtendedOp lhs rhs diff borrow =
  MkOp "arith.subui_extended" [lhs, rhs] [] [] [] [diff, borrow]

||| `arith.truncf`: cast from floating-point to narrower floating-point
export
truncfOp : {default Nothing roundingmode : Maybe RoundingMode} -> {default Nothing fastmath : Maybe MlirAttr} -> (in' : Value) -> (out : MlirType) -> Op
truncfOp in' out =
  MkOp "arith.truncf" [in'] (attrIf "roundingmode" (\v => integerAttr (roundingModeValue v) (integerType 32)) roundingmode ++ attrIf "fastmath" id fastmath) [] [] [out]

||| `arith.trunci`: integer truncation operation
export
trunciOp : {default Nothing overflowFlags : Maybe MlirAttr} -> (in' : Value) -> (out : MlirType) -> Op
trunciOp in' out =
  MkOp "arith.trunci" [in'] (attrIf "overflowFlags" id overflowFlags) [] [] [out]

||| `arith.uitofp`: cast from unsigned integer type to floating-point
export
uitofpOp : {default False nonNeg : Bool} -> (in' : Value) -> (out : MlirType) -> Op
uitofpOp in' out =
  MkOp "arith.uitofp" [in'] (unitIf "nonNeg" nonNeg) [] [] [out]

||| `arith.xori`: integer binary xor
export
xoriOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
xoriOp lhs rhs result =
  MkOp "arith.xori" [lhs, rhs] [] [] [] [result]

-- Not generated:
-- attribute FastMathFlagsAttr: its parameter `value` is the C++ `::mlir::arith::FastMathFlags`
-- attribute IntegerOverflowFlagsAttr: its parameter `value` is the C++ `::mlir::arith::IntegerOverflowFlags`
-- fingerprint: 1253639017-898706 790948507-18668
