||| The builtin dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.Builtin

import IdrisMLIR.MLIR
import IdrisMLIR.Syntax.Builtin

%default total

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `builtin.module`: A top level container operation
export
moduleOp : {default Nothing symName : Maybe String} -> {default Nothing symVisibility : Maybe String} -> (bodyRegion : Region) -> Op
moduleOp bodyRegion =
  MkOp "builtin.module" [] (attrIf "sym_name" StringAttr symName ++ attrIf "sym_visibility" StringAttr symVisibility) [bodyRegion] [] []

||| `builtin.unrealized_conversion_cast`: An unrealized conversion from one set of types to another
export
unrealizedConversionCastOp : (inputs : List Value) -> (outputs : List MlirType) -> Op
unrealizedConversionCastOp inputs outputs =
  MkOp "builtin.unrealized_conversion_cast" inputs [] [] [] outputs

-- fingerprint: 2410526247-521931 1133266708-1092
