||| The idr dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.Idr

import IdrisMLIR.MLIR

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace CmpPredicate
  ||| a comparison of strings or bigs
  public export
  data CmpPredicate = Eq | Lt | Lte | Gt | Gte

-- The value that stands for a CmpPredicate, as the ops below write it.
cmpPredicateValue : CmpPredicate -> Integer
cmpPredicateValue CmpPredicate.Eq = 0
cmpPredicateValue CmpPredicate.Lt = 1
cmpPredicateValue CmpPredicate.Lte = 2
cmpPredicateValue CmpPredicate.Gt = 3
cmpPredicateValue CmpPredicate.Gte = 4

------------------------------------------------------------------------------
-- Types and attributes
------------------------------------------------------------------------------

||| `!idr.big`: an Integer
export
bigType : MlirType
bigType = MkMlirType "!idr.big"

||| `!idr.box`: a value of the boxed type declared by idr.data ... box
export
boxType : (name : String) -> MlirType
boxType name = MkMlirType ("!idr.box<" ++ (flatSymbolRefAttr name).text ++ ">")

||| `!idr.data`: a value of the unboxed sum declared by idr.data
export
dataType : (name : String) -> MlirType
dataType name = MkMlirType ("!idr.data<" ++ (flatSymbolRefAttr name).text ++ ">")

||| `!idr.dest`: a field of a cell built without it, to be written exactly once
export
destType : (value : MlirType) -> MlirType
destType value = MkMlirType ("!idr.dest<" ++ value.text ++ ">")

||| `!idr.nat`: a natural number: a non-negative big
export
natType : MlirType
natType = MkMlirType "!idr.nat"

||| `!idr.str`: a string (UTF-8)
export
strType : MlirType
strType = MkMlirType "!idr.str"

||| `!idr.token`: the memory of a cell whose fields idr.take moved out, or null
export
tokenType : MlirType
tokenType = MkMlirType "!idr.token"

||| `!idr.world`: the IO world token
export
worldType : MlirType
worldType = MkMlirType "!idr.world"

||| `#idr.big`: an integer of any size, in canonical decimal
export
bigAttr : (value : String) -> MlirAttr
bigAttr value = MkMlirAttr ("#idr.big<" ++ (stringAttr value).text ++ ">")

||| `#idr.clone`: a clone, named, and the key it is the function of
export
cloneAttr : (function : String) -> (key : MlirAttr) -> MlirAttr
cloneAttr function key = MkMlirAttr ("#idr.clone<" ++ (flatSymbolRefAttr function).text ++ ", " ++ key.text ++ ">")

||| `#idr.closure`: a closure of a function with its captures as attributes
export
closureAttr : (callee : String) -> (captures : List MlirAttr) -> MlirAttr
closureAttr callee captures = MkMlirAttr ("#idr.closure<" ++ (flatSymbolRefAttr callee).text ++ ", " ++ (arrayAttr captures).text ++ ">")

||| `#idr.con`: a constructor of a sum or box, its fields as attributes
export
conAttr : (ctor : List String) -> (fields : List MlirAttr) -> MlirAttr
conAttr ctor fields = MkMlirAttr ("#idr.con<" ++ (symbolRefAttr ctor).text ++ ", " ++ (arrayAttr fields).text ++ ">")

||| `#idr.erased`: the erased value
export
erasedAttr : MlirAttr
erasedAttr = MkMlirAttr "#idr.erased"

||| `#idr.key_apply`: the key of a clone that applies its callee's result
export
keyApplyAttr : (callee : String) -> (arity : Nat) -> MlirAttr
keyApplyAttr callee arity = MkMlirAttr ("#idr.key_apply<" ++ (stringAttr callee).text ++ ", " ++ show arity ++ ">")

||| `#idr.key_apply_field`: the key of a clone that applies field `index` of `ctor` of its callee's result
export
keyApplyFieldAttr : (callee : String) -> (arity : Nat) -> (ctor : String) -> (index : Nat) -> MlirAttr
keyApplyFieldAttr callee arity ctor index = MkMlirAttr ("#idr.key_apply_field<" ++ (stringAttr callee).text ++ ", " ++ show arity ++ ", " ++ (stringAttr ctor).text ++ ", " ++ show index ++ ">")

||| `#idr.key_closure`: a closure of `callee` in a key, over the patterns of its captures
export
keyClosureAttr : (callee : String) -> (captures : List MlirAttr) -> MlirAttr
keyClosureAttr callee captures = MkMlirAttr ("#idr.key_closure<" ++ (stringAttr callee).text ++ ", " ++ (arrayAttr captures).text ++ ">")

||| `#idr.key_con`: a constructor `@data::@ctor` in a key, over the patterns of its fields
export
keyConAttr : (data' : String) -> (ctor : String) -> (fields : List MlirAttr) -> MlirAttr
keyConAttr data' ctor fields = MkMlirAttr ("#idr.key_con<" ++ (stringAttr data').text ++ ", " ++ (stringAttr ctor).text ++ ", " ++ (arrayAttr fields).text ++ ">")

||| `#idr.key_hole`: a runtime leaf of a key: the clone's parameter that holds it
export
keyHoleAttr : (index : Nat) -> MlirAttr
keyHoleAttr index = MkMlirAttr ("#idr.key_hole<" ++ show index ++ ">")

||| `#idr.spec_key`: the key of a clone that specializes
export
specKeyAttr : (origin : String) -> (patterns : List MlirAttr) -> MlirAttr
specKeyAttr origin patterns = MkMlirAttr ("#idr.spec_key<" ++ (stringAttr origin).text ++ ", " ++ (arrayAttr patterns).text ++ ">")

||| The discardable attribute `idr.program`.
export
programDiscardable : NamedAttr
programDiscardable = ("idr.program", unitAttr)

||| The discardable attribute `idr.stage`.
export
stageDiscardable : String -> NamedAttr
stageDiscardable s = ("idr.stage", stringAttr s)

||| The discardable attribute `idr.total`.
export
totalDiscardable : NamedAttr
totalDiscardable = ("idr.total", unitAttr)

||| The discardable attribute `idr.break_last`.
export
breakLastDiscardable : NamedAttr
breakLastDiscardable = ("idr.break_last", unitAttr)

||| The discardable attribute `idr.effects`.
export
effectsDiscardable : MlirAttr -> NamedAttr
effectsDiscardable a = ("idr.effects", a)

||| The discardable attribute `idr.stack`.
export
stackDiscardable : NamedAttr
stackDiscardable = ("idr.stack", unitAttr)

||| The discardable attribute `idr.clone`.
export
cloneDiscardable : MlirAttr -> NamedAttr
cloneDiscardable a = ("idr.clone", a)

||| The discardable attribute `idr.hole`.
export
holeDiscardable : MlirAttr -> NamedAttr
holeDiscardable a = ("idr.hole", a)

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `idr.apply`: applies a closure to arguments
export
applyOp : {default Nothing argAttrs : Maybe (List MlirAttr)} -> {default Nothing resAttrs : Maybe (List MlirAttr)} -> (callee : Value) -> (args : List Value) -> (results : List MlirType) -> Op
applyOp callee args results =
  MkOp "idr.apply" (concat [[callee], args]) (attrIf "arg_attrs" arrayAttr argAttrs ++ attrIf "res_attrs" arrayAttr resAttrs) [] [] results

||| `idr.array.fold`: an array folded from the left in index order
export
arrayFoldOp : (array : Value) -> (init : Value) -> (world : Value) -> (body : Region) -> (result : MlirType) -> (next : MlirType) -> Op
arrayFoldOp array init world body result next =
  MkOp "idr.array.fold" [array, init, world] [] [body] [] [result, next]

||| `idr.array.generate`: a new array of the body's value at each index
export
arrayGenerateOp : (size : Value) -> (fill : Value) -> (world : Value) -> (body : Region) -> (array : MlirType) -> (next : MlirType) -> Op
arrayGenerateOp size fill world body array next =
  MkOp "idr.array.generate" [size, fill, world] [] [body] [] [array, next]

||| `idr.array.get`: the element of an array at an index
export
arrayGetOp : (array : Value) -> (index : Value) -> (world : Value) -> (value : MlirType) -> (next : MlirType) -> Op
arrayGetOp array index world value next =
  MkOp "idr.array.get" [array, index, world] [] [] [] [value, next]

||| `idr.array.new`: a new array of `size` copies of `fill`
export
arrayNewOp : (size : Value) -> (fill : Value) -> (world : Value) -> (array : MlirType) -> (next : MlirType) -> Op
arrayNewOp size fill world array next =
  MkOp "idr.array.new" [size, fill, world] [] [] [] [array, next]

||| `idr.array.set`: writes an element of an array at an index
export
arraySetOp : (array : Value) -> (index : Value) -> (value : Value) -> (world : Value) -> (next : MlirType) -> Op
arraySetOp array index value world next =
  MkOp "idr.array.set" [array, index, value, world] [] [] [] [next]

||| `idr.big.add`: the sum of two bigs or two naturals
export
bigAddOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigAddOp lhs rhs result =
  MkOp "idr.big.add" [lhs, rhs] [] [] [] [result]

||| `idr.big.and`: the bitwise and of two bigs
export
bigAndOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigAndOp lhs rhs result =
  MkOp "idr.big.and" [lhs, rhs] [] [] [] [result]

||| `idr.big.cmp`: compares two bigs or two naturals
export
bigCmpOp : (predicate : CmpPredicate) -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigCmpOp predicate lhs rhs result =
  MkOp "idr.big.cmp" [lhs, rhs] [("predicate", integerAttr (cmpPredicateValue predicate) (integerType 64))] [] [] [result]

||| `idr.big.div`: the quotient of two bigs, as Integer's div and mod; crashes on zero
export
bigDivOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigDivOp lhs rhs result =
  MkOp "idr.big.div" [lhs, rhs] [] [] [] [result]

||| `idr.big.from_double`: a Double truncated to a big; crashes on NaN and the infinities
export
bigFromDoubleOp : (value : Value) -> (result : MlirType) -> Op
bigFromDoubleOp value result =
  MkOp "idr.big.from_double" [value] [] [] [] [result]

||| `idr.big.from_int`: an integer as a big or, unsigned, as a natural
export
bigFromIntOp : {default False isSigned : Bool} -> (value : Value) -> (result : MlirType) -> Op
bigFromIntOp value result =
  MkOp "idr.big.from_int" [value] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.big.from_str`: a string as a big, as prim__cast_StringInteger reads it
export
bigFromStrOp : (str : Value) -> (result : MlirType) -> Op
bigFromStrOp str result =
  MkOp "idr.big.from_str" [str] [] [] [] [result]

||| `idr.big.mod`: the remainder of two bigs, as Integer's div and mod; crashes on zero
export
bigModOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigModOp lhs rhs result =
  MkOp "idr.big.mod" [lhs, rhs] [] [] [] [result]

||| `idr.big.mul`: the product of two bigs or two naturals
export
bigMulOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigMulOp lhs rhs result =
  MkOp "idr.big.mul" [lhs, rhs] [] [] [] [result]

||| `idr.big.neg`: the negation of a big
export
bigNegOp : (value : Value) -> (result : MlirType) -> Op
bigNegOp value result =
  MkOp "idr.big.neg" [value] [] [] [] [result]

||| `idr.big.or`: the bitwise or of two bigs
export
bigOrOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigOrOp lhs rhs result =
  MkOp "idr.big.or" [lhs, rhs] [] [] [] [result]

||| `idr.big.pred`: the predecessor of a natural that is not zero
export
bigPredOp : (value : Value) -> (result : MlirType) -> Op
bigPredOp value result =
  MkOp "idr.big.pred" [value] [] [] [] [result]

||| `idr.big.show`: the decimal text of a big
export
bigShowOp : (value : Value) -> (result : MlirType) -> Op
bigShowOp value result =
  MkOp "idr.big.show" [value] [] [] [] [result]

||| `idr.big.small`: the small big or natural of a word that fits
export
bigSmallOp : (value : Value) -> (result : MlirType) -> Op
bigSmallOp value result =
  MkOp "idr.big.small" [value] [] [] [] [result]

||| `idr.big.sub`: the difference of two bigs
export
bigSubOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigSubOp lhs rhs result =
  MkOp "idr.big.sub" [lhs, rhs] [] [] [] [result]

||| `idr.big.to_double`: a big as the nearest Double
export
bigToDoubleOp : (value : Value) -> (result : MlirType) -> Op
bigToDoubleOp value result =
  MkOp "idr.big.to_double" [value] [] [] [] [result]

||| `idr.big.to_int`: a big or a natural as an integer, wrapped to its width
export
bigToIntOp : (value : Value) -> (result : MlirType) -> Op
bigToIntOp value result =
  MkOp "idr.big.to_int" [value] [] [] [] [result]

||| `idr.big.xor`: the bitwise xor of two bigs
export
bigXorOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
bigXorOp lhs rhs result =
  MkOp "idr.big.xor" [lhs, rhs] [] [] [] [result]

||| `idr.borrow`: a view of an owned value, alive while its owner holds its reference
export
borrowOp : (value : Value) -> (result : MlirType) -> Op
borrowOp value result =
  MkOp "idr.borrow" [value] [] [] [] [result]

||| `idr.closure`: a closure of a function: its leading parameters are the captures
export
closureOp : (callee : String) -> (captures : List Value) -> (result : MlirType) -> Op
closureOp callee captures result =
  MkOp "idr.closure" captures [("callee", flatSymbolRefAttr callee)] [] [] [result]

||| `idr.con`: builds a constructor value
export
conOp : (ctor : List String) -> (fields : List Value) -> (result : MlirType) -> Op
conOp ctor fields result =
  MkOp "idr.con" fields [("ctor", symbolRefAttr ctor)] [] [] [result]

||| `idr.constant`: a constant: a constructor, closure, string, big or the erased value
export
constantOp : (value : MlirAttr) -> (result : MlirType) -> Op
constantOp value result =
  MkOp "idr.constant" [] [("value", value)] [] [] [result]

||| `idr.crash`: ends the program with a message naming the cause
export
crashOp : (message : String) -> Op
crashOp message =
  MkOp "idr.crash" [] [("message", stringAttr message)] [] [] []

||| `idr.crash_str`: ends the program with a string's text
export
crashStrOp : (message : Value) -> Op
crashStrOp message =
  MkOp "idr.crash_str" [message] [] [] [] []

||| `idr.ctor`: declares one constructor of an idr.data type
export
ctorOp : (symName : String) -> (fieldTypes : List MlirType) -> Op
ctorOp symName fieldTypes =
  MkOp "idr.ctor" [] [("sym_name", stringAttr symName), ("field_types", typeArrayAttr fieldTypes)] [] [] []

||| `idr.data`: declares a monomorphic data type, unboxed or boxed
export
dataOp : {default False box : Bool} -> {default False closures : Bool} -> (symName : String) -> (body : Region) -> Op
dataOp symName body =
  MkOp "idr.data" [] ([("sym_name", stringAttr symName)] ++ unitIf "box" box ++ unitIf "closures" closures) [body] [] []

||| `idr.dest.of`: the destination that is a pending field of a cell just built
export
destOfOp : (value : Value) -> (ctor : String) -> (index : Integer) -> (result : MlirType) -> Op
destOfOp value ctor index result =
  MkOp "idr.dest.of" [value] [("ctor", flatSymbolRefAttr ctor), ("index", integerAttr index (integerType 64))] [] [] [result]

||| `idr.dest.pending`: the operand of a constructor for a field it is built without
export
destPendingOp : (result : MlirType) -> Op
destPendingOp result =
  MkOp "idr.dest.pending" [] [] [] [] [result]

||| `idr.dest.write`: writes the value of a pending field, consuming its reference
export
destWriteOp : (dest : Value) -> (value : Value) -> Op
destWriteOp dest value =
  MkOp "idr.dest.write" [dest, value] [] [] [] []

||| `idr.div`: Idris div: Euclidean when signed, crashes on zero
export
divOp : {default False isSigned : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
divOp lhs rhs result =
  MkOp "idr.div" [lhs, rhs] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.double_head`: the first character of a Double's text
export
doubleHeadOp : (value : Value) -> (result : MlirType) -> Op
doubleHeadOp value result =
  MkOp "idr.double_head" [value] [] [] [] [result]

||| `idr.drop`: consumes a reference, and frees the value with its last
export
dropOp : (value : Value) -> Op
dropOp value =
  MkOp "idr.drop" [value] [] [] [] []

||| `idr.dup`: a reference of its own to a value that holds none
export
dupOp : (value : Value) -> (result : MlirType) -> Op
dupOp value result =
  MkOp "idr.dup" [value] [] [] [] [result]

||| `idr.field`: reads a field of a constructor value
export
fieldOp : (value : Value) -> (ctor : String) -> (index : Integer) -> (result : MlirType) -> Op
fieldOp value ctor index result =
  MkOp "idr.field" [value] [("ctor", flatSymbolRefAttr ctor), ("index", integerAttr index (integerType 64))] [] [] [result]

||| `idr.int_head`: the first character of an integer's decimal text
export
intHeadOp : {default False isSigned : Bool} -> (value : Value) -> (result : MlirType) -> Op
intHeadOp value result =
  MkOp "idr.int_head" [value] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.io.buffer_copy`: bytes copied from one buffer into another
export
ioBufferCopyOp : (src : Value) -> (srcOffset : Value) -> (len : Value) -> (dst : Value) -> (dstOffset : Value) -> (world : Value) -> (next : MlirType) -> Op
ioBufferCopyOp src srcOffset len dst dstOffset world next =
  MkOp "idr.io.buffer_copy" [src, srcOffset, len, dst, dstOffset, world] [] [] [] [next]

||| `idr.io.buffer_get_string`: a buffer's bytes read as a string
export
ioBufferGetStringOp : (buffer : Value) -> (offset : Value) -> (len : Value) -> (world : Value) -> (str : MlirType) -> (next : MlirType) -> Op
ioBufferGetStringOp buffer offset len world str next =
  MkOp "idr.io.buffer_get_string" [buffer, offset, len, world] [] [] [] [str, next]

||| `idr.io.buffer_load`: a machine word read from a buffer at a byte offset
export
ioBufferLoadOp : (buffer : Value) -> (offset : Value) -> (world : Value) -> (value : MlirType) -> (next : MlirType) -> Op
ioBufferLoadOp buffer offset world value next =
  MkOp "idr.io.buffer_load" [buffer, offset, world] [] [] [] [value, next]

||| `idr.io.buffer_set_string`: a string's bytes written into a buffer
export
ioBufferSetStringOp : (buffer : Value) -> (offset : Value) -> (str : Value) -> (world : Value) -> (next : MlirType) -> Op
ioBufferSetStringOp buffer offset str world next =
  MkOp "idr.io.buffer_set_string" [buffer, offset, str, world] [] [] [] [next]

||| `idr.io.buffer_store`: a machine word written into a buffer at a byte offset
export
ioBufferStoreOp : (buffer : Value) -> (offset : Value) -> (value : Value) -> (world : Value) -> (next : MlirType) -> Op
ioBufferStoreOp buffer offset value world next =
  MkOp "idr.io.buffer_store" [buffer, offset, value, world] [] [] [] [next]

||| `idr.io.eof`
export
ioEofOp : (handle : Value) -> (world : Value) -> (ended : MlirType) -> (next : MlirType) -> Op
ioEofOp handle world ended next =
  MkOp "idr.io.eof" [handle, world] [] [] [] [ended, next]

||| `idr.io.get_byte`
export
ioGetByteOp : (world : Value) -> (ch : MlirType) -> (next : MlirType) -> Op
ioGetByteOp world ch next =
  MkOp "idr.io.get_byte" [world] [] [] [] [ch, next]

||| `idr.io.get_line`
export
ioGetLineOp : (world : Value) -> (str : MlirType) -> (next : MlirType) -> Op
ioGetLineOp world str next =
  MkOp "idr.io.get_line" [world] [] [] [] [str, next]

||| `idr.io.put_char`
export
ioPutCharOp : (ch : Value) -> (world : Value) -> (next : MlirType) -> Op
ioPutCharOp ch world next =
  MkOp "idr.io.put_char" [ch, world] [] [] [] [next]

||| `idr.io.put_double`
export
ioPutDoubleOp : (value : Value) -> (world : Value) -> (next : MlirType) -> Op
ioPutDoubleOp value world next =
  MkOp "idr.io.put_double" [value, world] [] [] [] [next]

||| `idr.io.put_int`
export
ioPutIntOp : {default False isSigned : Bool} -> (value : Value) -> (world : Value) -> (next : MlirType) -> Op
ioPutIntOp value world next =
  MkOp "idr.io.put_int" [value, world] (unitIf "is_signed" isSigned) [] [] [next]

||| `idr.io.put_list`: writes the characters or the strings of a list, in order
export
ioPutListOp : (list : Value) -> (world : Value) -> (next : MlirType) -> Op
ioPutListOp list world next =
  MkOp "idr.io.put_list" [list, world] [] [] [] [next]

||| `idr.io.put_str`
export
ioPutStrOp : (str : Value) -> (world : Value) -> (next : MlirType) -> Op
ioPutStrOp str world next =
  MkOp "idr.io.put_str" [str, world] [] [] [] [next]

||| `idr.io.read_bytes`
export
ioReadBytesOp : (handle : Value) -> (buffer : Value) -> (offset : Value) -> (count : Value) -> (world : Value) -> (read : MlirType) -> (next : MlirType) -> Op
ioReadBytesOp handle buffer offset count world read next =
  MkOp "idr.io.read_bytes" [handle, buffer, offset, count, world] [] [] [] [read, next]

||| `idr.io.write_bytes`
export
ioWriteBytesOp : (handle : Value) -> (buffer : Value) -> (offset : Value) -> (count : Value) -> (world : Value) -> (written : MlirType) -> (next : MlirType) -> Op
ioWriteBytesOp handle buffer offset count world written next =
  MkOp "idr.io.write_bytes" [handle, buffer, offset, count, world] [] [] [] [written, next]

||| `idr.lin.enter`: a value handed to a linear position
export
linEnterOp : (value : Value) -> (result : MlirType) -> Op
linEnterOp value result =
  MkOp "idr.lin.enter" [value] [] [] [] [result]

||| `idr.lin.use`: the one use of a linear value
export
linUseOp : (linear : Value) -> (result : MlirType) -> Op
linUseOp linear result =
  MkOp "idr.lin.use" [linear] [] [] [] [result]

||| `idr.match`: branches on the constructor of a sum or box, taking it apart at its grade
export
matchOp : (scrutinee : Value) -> (cases : List MlirAttr) -> (regions : List Region) -> (results : List MlirType) -> Op
matchOp scrutinee cases regions results =
  MkOp "idr.match" [scrutinee] [("cases", arrayAttr cases)] regions [] results

||| `idr.match_lit`: branches on the value of a condition, integer, string, big or natural
export
matchLitOp : (scrutinee : Value) -> (cases : List MlirAttr) -> (regions : List Region) -> (results : List MlirType) -> Op
matchLitOp scrutinee cases regions results =
  MkOp "idr.match_lit" [scrutinee] [("cases", arrayAttr cases)] regions [] results

||| `idr.may_loop`: marks one iteration of a loop that may not terminate
export
mayLoopOp : Op
mayLoopOp =
  MkOp "idr.may_loop" [] [] [] [] []

||| `idr.mod`: Idris mod: Euclidean when signed, crashes on zero
export
modOp : {default False isSigned : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
modOp lhs rhs result =
  MkOp "idr.mod" [lhs, rhs] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.nat.from_big`: an Integer as a natural, 0 if it is negative
export
natFromBigOp : (value : Value) -> (result : MlirType) -> Op
natFromBigOp value result =
  MkOp "idr.nat.from_big" [value] [] [] [] [result]

||| `idr.nat.to_big`: a natural as an Integer
export
natToBigOp : (value : Value) -> (result : MlirType) -> Op
natToBigOp value result =
  MkOp "idr.nat.to_big" [value] [] [] [] [result]

||| `idr.reuse`: builds a boxed constructor in a token's cell, or in a new one when it is null
export
reuseOp : (token : Value) -> (ctor : List String) -> (fields : List Value) -> (result : MlirType) -> Op
reuseOp token ctor fields result =
  MkOp "idr.reuse" (concat [[token], fields]) [("ctor", symbolRefAttr ctor)] [] [] [result]

||| `idr.share`: gives an owned value on as owned, whatever it alone reached
export
shareOp : (value : Value) -> (result : MlirType) -> Op
shareOp value result =
  MkOp "idr.share" [value] [] [] [] [result]

||| `idr.shl`: Idris shiftL: defined for every amount, wrapped to the width
export
shlOp : {default False isSigned : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
shlOp lhs rhs result =
  MkOp "idr.shl" [lhs, rhs] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.shr`: Idris shiftR: arithmetic, defined for every amount
export
shrOp : {default False isSigned : Bool} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
shrOp lhs rhs result =
  MkOp "idr.shr" [lhs, rhs] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.str.append`: the concatenation of two strings
export
strAppendOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
strAppendOp lhs rhs result =
  MkOp "idr.str.append" [lhs, rhs] [] [] [] [result]

||| `idr.str.bytes_length`: the number of bytes of a string
export
strBytesLengthOp : (str : Value) -> (result : MlirType) -> Op
strBytesLengthOp str result =
  MkOp "idr.str.bytes_length" [str] [] [] [] [result]

||| `idr.str.cmp`: compares two strings
export
strCmpOp : (predicate : CmpPredicate) -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
strCmpOp predicate lhs rhs result =
  MkOp "idr.str.cmp" [lhs, rhs] [("predicate", integerAttr (cmpPredicateValue predicate) (integerType 64))] [] [] [result]

||| `idr.str.concat`: the concatenation of a list of strings, built once
export
strConcatOp : (list : Value) -> (result : MlirType) -> Op
strConcatOp list result =
  MkOp "idr.str.concat" [list] [] [] [] [result]

||| `idr.str.cons`: a character before a string
export
strConsOp : (head : Value) -> (tail : Value) -> (result : MlirType) -> Op
strConsOp head tail result =
  MkOp "idr.str.cons" [head, tail] [] [] [] [result]

||| `idr.str.from_char`: the string of one character
export
strFromCharOp : (value : Value) -> (result : MlirType) -> Op
strFromCharOp value result =
  MkOp "idr.str.from_char" [value] [] [] [] [result]

||| `idr.str.head`: the first character of a string; crashes on ""
export
strHeadOp : (str : Value) -> (result : MlirType) -> Op
strHeadOp str result =
  MkOp "idr.str.head" [str] [] [] [] [result]

||| `idr.str.index`: the character at an index; crashes out of range
export
strIndexOp : (str : Value) -> (index : Value) -> (result : MlirType) -> Op
strIndexOp str index result =
  MkOp "idr.str.index" [str, index] [] [] [] [result]

||| `idr.str.length`: the number of characters of a string
export
strLengthOp : (str : Value) -> (result : MlirType) -> Op
strLengthOp str result =
  MkOp "idr.str.length" [str] [] [] [] [result]

||| `idr.str.pack`: the string of a list of characters, built once
export
strPackOp : (list : Value) -> (result : MlirType) -> Op
strPackOp list result =
  MkOp "idr.str.pack" [list] [] [] [] [result]

||| `idr.str.reverse`: the characters of a string in reverse order
export
strReverseOp : (str : Value) -> (result : MlirType) -> Op
strReverseOp str result =
  MkOp "idr.str.reverse" [str] [] [] [] [result]

||| `idr.str.show`: the text of a number, as prim__cast_TString writes it
export
strShowOp : {default False isSigned : Bool} -> (value : Value) -> (result : MlirType) -> Op
strShowOp value result =
  MkOp "idr.str.show" [value] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.str.substr`: the characters of a string from a start, at most a length
export
strSubstrOp : (str : Value) -> (start : Value) -> (length' : Value) -> (result : MlirType) -> Op
strSubstrOp str start length' result =
  MkOp "idr.str.substr" [str, start, length'] [] [] [] [result]

||| `idr.str.tail`: a string without its first character; crashes on ""
export
strTailOp : (str : Value) -> (result : MlirType) -> Op
strTailOp str result =
  MkOp "idr.str.tail" [str] [] [] [] [result]

||| `idr.str.to_double`: a string as a Double, as prim__cast_StringDouble reads it
export
strToDoubleOp : (str : Value) -> (result : MlirType) -> Op
strToDoubleOp str result =
  MkOp "idr.str.to_double" [str] [] [] [] [result]

||| `idr.str.to_int`: a string as an integer, as prim__cast_StringT reads it
export
strToIntOp : {default False isSigned : Bool} -> (str : Value) -> (result : MlirType) -> Op
strToIntOp str result =
  MkOp "idr.str.to_int" [str] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.tag`: the constructor tag of a value
export
tagOp : (value : Value) -> (result : MlirType) -> Op
tagOp value result =
  MkOp "idr.tag" [value] [] [] [] [result]

||| `idr.take`: consumes a constructor value, each of its fields keeping a reference of its own
export
takeOp : (value : Value) -> (ctor : List String) -> (results : List MlirType) -> Op
takeOp value ctor results =
  MkOp "idr.take" [value] [("ctor", symbolRefAttr ctor)] [] [] results

||| `idr.to_byte`: an Int as a byte: itself when 0 to 255, else a crash
export
toByteOp : (value : Value) -> (result : MlirType) -> Op
toByteOp value result =
  MkOp "idr.to_byte" [value] [] [] [] [result]

||| `idr.to_char`: an integer as a Char: itself if a scalar value, else 0
export
toCharOp : {default False isSigned : Bool} -> (value : Value) -> (result : MlirType) -> Op
toCharOp value result =
  MkOp "idr.to_char" [value] (unitIf "is_signed" isSigned) [] [] [result]

||| `idr.to_int`: a Double as an integer, truncated and wrapped
export
toIntOp : (value : Value) -> (result : MlirType) -> Op
toIntOp value result =
  MkOp "idr.to_int" [value] [] [] [] [result]

||| `idr.world.new`: a forged world, the first of a chain of its own
export
worldNewOp : (world : MlirType) -> Op
worldNewOp world =
  MkOp "idr.world.new" [] [] [] [] [world]

||| `idr.yield`: ends a region of a match, or the body of an array loop, with its results
export
yieldOp : (results : List Value) -> Op
yieldOp results =
  MkOp "idr.yield" results [] [] [] []

-- Not generated:
-- type FnType: its syntax is C++
-- type QType: its parameter `grade` is the C++ `::idr::Grade`
-- attribute EffectAttr: its parameter `value` is the C++ `::idr::Effect`
-- fingerprint: 489305660-956607 941377407-28833
