||| The math dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.Math

import IdrisMLIR.MLIR
import IdrisMLIR.Syntax.Math

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

-- The value that stands for a RoundingMode, as the ops below write it.
roundingModeValue : RoundingMode -> Integer
roundingModeValue RoundingMode.ToNearestEven = 0
roundingModeValue RoundingMode.Downward = 1
roundingModeValue RoundingMode.Upward = 2
roundingModeValue RoundingMode.TowardZero = 3
roundingModeValue RoundingMode.ToNearestAway = 4

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `math.absf`: floating point absolute-value operation
export
absfOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
absfOp operand result =
  MkOp "math.absf" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.absi`: integer absolute-value operation
export
absiOp : (operand : Value) -> (result : MlirType) -> Op
absiOp operand result =
  MkOp "math.absi" [operand] [] [] [] [result]

||| `math.acos`: arcus cosine of the specified value
export
acosOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
acosOp operand result =
  MkOp "math.acos" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.acosh`: Hyperbolic arcus cosine of the given value
export
acoshOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
acoshOp operand result =
  MkOp "math.acosh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.asin`: arcus sine of the given value
export
asinOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
asinOp operand result =
  MkOp "math.asin" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.asinh`: hyperbolic arcus sine of the given value
export
asinhOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
asinhOp operand result =
  MkOp "math.asinh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.atan`: arcus tangent of the given value
export
atanOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
atanOp operand result =
  MkOp "math.atan" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.atan2`: 2-argument arcus tangent of the given values
export
atan2Op : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
atan2Op lhs rhs result =
  MkOp "math.atan2" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.atanh`: hyperbolic arcus tangent of the given value
export
atanhOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
atanhOp operand result =
  MkOp "math.atanh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.cbrt`: cube root of the specified value
export
cbrtOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
cbrtOp operand result =
  MkOp "math.cbrt" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.ceil`: ceiling of the specified value
export
ceilOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
ceilOp operand result =
  MkOp "math.ceil" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.clampf`: floating point clamping operation
export
clampfOp : {default Nothing fastmath : Maybe MlirAttr} -> (value : Value) -> (min : Value) -> (max : Value) -> (result : MlirType) -> Op
clampfOp value min max result =
  MkOp "math.clampf" [value, min, max] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.copysign`: A copysign operation
export
copysignOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
copysignOp lhs rhs result =
  MkOp "math.copysign" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.cos`: cosine of the specified value
export
cosOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
cosOp operand result =
  MkOp "math.cos" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.cosh`: hyperbolic cosine of the specified value
export
coshOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
coshOp operand result =
  MkOp "math.cosh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.ctlz`: counts the leading zeros an integer value
export
ctlzOp : (operand : Value) -> (result : MlirType) -> Op
ctlzOp operand result =
  MkOp "math.ctlz" [operand] [] [] [] [result]

||| `math.ctpop`: counts the number of set bits of an integer value
export
ctpopOp : (operand : Value) -> (result : MlirType) -> Op
ctpopOp operand result =
  MkOp "math.ctpop" [operand] [] [] [] [result]

||| `math.cttz`: counts the trailing zeros an integer value
export
cttzOp : (operand : Value) -> (result : MlirType) -> Op
cttzOp operand result =
  MkOp "math.cttz" [operand] [] [] [] [result]

||| `math.erf`: error function of the specified value
export
erfOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
erfOp operand result =
  MkOp "math.erf" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.erfc`: complementary error function of the specified value
export
erfcOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
erfcOp operand result =
  MkOp "math.erfc" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.exp`: base-e exponential of the specified value
export
expOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
expOp operand result =
  MkOp "math.exp" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.exp2`: base-2 exponential of the specified value
export
exp2Op : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
exp2Op operand result =
  MkOp "math.exp2" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.expm1`: base-e exponential of the specified value minus 1
export
expm1Op : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
expm1Op operand result =
  MkOp "math.expm1" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.floor`: floor of the specified value
export
floorOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
floorOp operand result =
  MkOp "math.floor" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.fma`: floating point fused multipy-add operation
export
fmaOp : {default Nothing fastmath : Maybe MlirAttr} -> {default Nothing roundingmode : Maybe RoundingMode} -> (a' : Value) -> (b : Value) -> (c : Value) -> (result : MlirType) -> Op
fmaOp a' b c result =
  MkOp "math.fma" [a', b, c] (attrIf "fastmath" id fastmath ++ attrIf "roundingmode" (\v => IntegerAttr (roundingModeValue v) (IntegerType 32)) roundingmode) [] [] [result]

||| `math.fpowi`: floating point raised to the signed integer power
export
fpowiOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
fpowiOp lhs rhs result =
  MkOp "math.fpowi" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.ipowi`: signed integer raised to the power of operation
export
ipowiOp : (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
ipowiOp lhs rhs result =
  MkOp "math.ipowi" [lhs, rhs] [] [] [] [result]

||| `math.isfinite`: returns true if the operand classifies as finite
export
isfiniteOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
isfiniteOp operand result =
  MkOp "math.isfinite" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.isinf`: returns true if the operand classifies as infinite
export
isinfOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
isinfOp operand result =
  MkOp "math.isinf" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.isnan`: returns true if the operand classifies as NaN
export
isnanOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
isnanOp operand result =
  MkOp "math.isnan" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.isnormal`: returns true if the operand classifies as normal
export
isnormalOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
isnormalOp operand result =
  MkOp "math.isnormal" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.log`: base-e logarithm of the specified value
export
logOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
logOp operand result =
  MkOp "math.log" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.log10`: base-10 logarithm of the specified value
export
log10Op : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
log10Op operand result =
  MkOp "math.log10" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.log1p`: Computes the natural logarithm of one plus the given value
export
log1pOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
log1pOp operand result =
  MkOp "math.log1p" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.log2`: base-2 logarithm of the specified value
export
log2Op : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
log2Op operand result =
  MkOp "math.log2" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.powf`: floating point raised to the power of operation
export
powfOp : {default Nothing fastmath : Maybe MlirAttr} -> (lhs : Value) -> (rhs : Value) -> (result : MlirType) -> Op
powfOp lhs rhs result =
  MkOp "math.powf" [lhs, rhs] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.round`: round of the specified value
export
roundOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
roundOp operand result =
  MkOp "math.round" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.roundeven`: round of the specified value with halfway cases to even
export
roundevenOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
roundevenOp operand result =
  MkOp "math.roundeven" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.rsqrt`: reciprocal of sqrt (1 / sqrt of the specified value)
export
rsqrtOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
rsqrtOp operand result =
  MkOp "math.rsqrt" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.sin`: sine of the specified value
export
sinOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
sinOp operand result =
  MkOp "math.sin" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.sincos`: sine and cosine of the specified value
export
sincosOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (sin : MlirType) -> (cos : MlirType) -> Op
sincosOp operand sin cos =
  MkOp "math.sincos" [operand] (attrIf "fastmath" id fastmath) [] [] [sin, cos]

||| `math.sinh`: hyperbolic sine of the specified value
export
sinhOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
sinhOp operand result =
  MkOp "math.sinh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.sqrt`: sqrt of the specified value
export
sqrtOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
sqrtOp operand result =
  MkOp "math.sqrt" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.tan`: tangent of the specified value
export
tanOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
tanOp operand result =
  MkOp "math.tan" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.tanh`: hyperbolic tangent of the specified value
export
tanhOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
tanhOp operand result =
  MkOp "math.tanh" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

||| `math.trunc`: trunc of the specified value
export
truncOp : {default Nothing fastmath : Maybe MlirAttr} -> (operand : Value) -> (result : MlirType) -> Op
truncOp operand result =
  MkOp "math.trunc" [operand] (attrIf "fastmath" id fastmath) [] [] [result]

-- fingerprint: 2756140796-759837 3305642322-13500
