||| The memref dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.MemRef

import IdrisMLIR.MLIR

%default total

------------------------------------------------------------------------------
-- Enums
------------------------------------------------------------------------------

namespace AtomicRMWKind
  ||| allowed 64-bit signless integer cases: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  public export
  data AtomicRMWKind = Addf | Addi | Andi | Assign | Maximumf | Maxnumf | Maxs | Maxu | Minimumf | Minnumf | Mins | Minu | Mulf | Muli | Ori | Xori

-- The value that stands for a AtomicRMWKind, as the ops below write it.
atomicRMWKindValue : AtomicRMWKind -> Integer
atomicRMWKindValue AtomicRMWKind.Addf = 0
atomicRMWKindValue AtomicRMWKind.Addi = 1
atomicRMWKindValue AtomicRMWKind.Andi = 2
atomicRMWKindValue AtomicRMWKind.Assign = 3
atomicRMWKindValue AtomicRMWKind.Maximumf = 4
atomicRMWKindValue AtomicRMWKind.Maxnumf = 5
atomicRMWKindValue AtomicRMWKind.Maxs = 6
atomicRMWKindValue AtomicRMWKind.Maxu = 7
atomicRMWKindValue AtomicRMWKind.Minimumf = 8
atomicRMWKindValue AtomicRMWKind.Minnumf = 9
atomicRMWKindValue AtomicRMWKind.Mins = 10
atomicRMWKindValue AtomicRMWKind.Minu = 11
atomicRMWKindValue AtomicRMWKind.Mulf = 12
atomicRMWKindValue AtomicRMWKind.Muli = 13
atomicRMWKindValue AtomicRMWKind.Ori = 14
atomicRMWKindValue AtomicRMWKind.Xori = 15

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `memref.alloc`: memory allocation operation
export
allocOp : {default Nothing alignment : Maybe Integer} -> (dynamicSizes : List Value) -> (symbolOperands : List Value) -> (memref : MlirType) -> Op
allocOp dynamicSizes symbolOperands memref =
  MkOp "memref.alloc" (concat [dynamicSizes, symbolOperands]) (attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment ++ [("operandSegmentSizes", segmentSizes [length dynamicSizes, length symbolOperands])]) [] [] [memref]

||| `memref.alloca`: stack memory allocation operation
export
allocaOp : {default Nothing alignment : Maybe Integer} -> (dynamicSizes : List Value) -> (symbolOperands : List Value) -> (memref : MlirType) -> Op
allocaOp dynamicSizes symbolOperands memref =
  MkOp "memref.alloca" (concat [dynamicSizes, symbolOperands]) (attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment ++ [("operandSegmentSizes", segmentSizes [length dynamicSizes, length symbolOperands])]) [] [] [memref]

||| `memref.alloca_scope`: explicitly delimited scope for stack allocation
export
allocaScopeOp : (bodyRegion : Region) -> (results : List MlirType) -> Op
allocaScopeOp bodyRegion results =
  MkOp "memref.alloca_scope" [] [] [bodyRegion] [] results

||| `memref.alloca_scope.return`: terminator for alloca_scope operation
export
allocaScopeReturnOp : (results : List Value) -> Op
allocaScopeReturnOp results =
  MkOp "memref.alloca_scope.return" results [] [] [] []

||| `memref.assume_alignment`: assumption that gives alignment information to the input memref
export
assumeAlignmentOp : (memref : Value) -> (alignment : Integer) -> (result : MlirType) -> Op
assumeAlignmentOp memref alignment result =
  MkOp "memref.assume_alignment" [memref] [("alignment", integerAttr alignment (integerType 32))] [] [] [result]

||| `memref.atomic_rmw`: atomic read-modify-write operation
export
atomicRmwOp : (kind : AtomicRMWKind) -> (value : Value) -> (memref : Value) -> (indices : List Value) -> (result : MlirType) -> Op
atomicRmwOp kind value memref indices result =
  MkOp "memref.atomic_rmw" (concat [[value], [memref], indices]) [("kind", integerAttr (atomicRMWKindValue kind) (integerType 64))] [] [] [result]

||| `memref.atomic_yield`: yield operation for GenericAtomicRMWOp
export
atomicYieldOp : (result : Value) -> Op
atomicYieldOp result =
  MkOp "memref.atomic_yield" [result] [] [] [] []

||| `memref.cast`: memref cast operation
export
castOp : (source : Value) -> (dest : MlirType) -> Op
castOp source dest =
  MkOp "memref.cast" [source] [] [] [] [dest]

||| `memref.collapse_shape`: operation to produce a memref with a smaller rank.
export
collapseShapeOp : (src : Value) -> (reassociation : List MlirAttr) -> (result : MlirType) -> Op
collapseShapeOp src reassociation result =
  MkOp "memref.collapse_shape" [src] [("reassociation", arrayAttr reassociation)] [] [] [result]

||| `memref.copy`
export
copyOp : (source : Value) -> (target : Value) -> Op
copyOp source target =
  MkOp "memref.copy" [source, target] [] [] [] []

||| `memref.dealloc`: memory deallocation operation
export
deallocOp : (memref : Value) -> Op
deallocOp memref =
  MkOp "memref.dealloc" [memref] [] [] [] []

||| `memref.dim`: dimension index operation
export
dimOp : (source : Value) -> (index : Value) -> (result : MlirType) -> Op
dimOp source index result =
  MkOp "memref.dim" [source, index] [] [] [] [result]

||| `memref.distinct_objects`: assumption that acesses to specific memrefs will never alias
export
distinctObjectsOp : (operands : List Value) -> (results : List MlirType) -> Op
distinctObjectsOp operands results =
  MkOp "memref.distinct_objects" operands [] [] [] results

||| `memref.dma_start`: non-blocking DMA operation that starts a transfer
export
dmaStartOp : (operands : List Value) -> Op
dmaStartOp operands =
  MkOp "memref.dma_start" operands [] [] [] []

||| `memref.dma_wait`: blocking DMA operation that waits for transfer completion
export
dmaWaitOp : (tagMemRef : Value) -> (tagIndices : List Value) -> (numElements : Value) -> Op
dmaWaitOp tagMemRef tagIndices numElements =
  MkOp "memref.dma_wait" (concat [[tagMemRef], tagIndices, [numElements]]) [] [] [] []

||| `memref.expand_shape`: operation to produce a memref with a higher rank.
export
expandShapeOp : (src : Value) -> (reassociation : List MlirAttr) -> (outputShape : List Value) -> (staticOutputShape : MlirAttr) -> (result : MlirType) -> Op
expandShapeOp src reassociation outputShape staticOutputShape result =
  MkOp "memref.expand_shape" (concat [[src], outputShape]) [("reassociation", arrayAttr reassociation), ("static_output_shape", staticOutputShape)] [] [] [result]

||| `memref.extract_aligned_pointer_as_index`: Extracts a memref's underlying aligned pointer as an index
export
extractAlignedPointerAsIndexOp : (source : Value) -> (alignedPointer : MlirType) -> Op
extractAlignedPointerAsIndexOp source alignedPointer =
  MkOp "memref.extract_aligned_pointer_as_index" [source] [] [] [] [alignedPointer]

||| `memref.extract_strided_metadata`: Extracts a buffer base with offset and strides
export
extractStridedMetadataOp : (source : Value) -> (baseBuffer : MlirType) -> (offset : MlirType) -> (sizes : List MlirType) -> (strides : List MlirType) -> Op
extractStridedMetadataOp source baseBuffer offset sizes strides =
  MkOp "memref.extract_strided_metadata" [source] [] [] [] (concat [[baseBuffer], [offset], sizes, strides])

||| `memref.generic_atomic_rmw`: atomic read-modify-write operation with a region
export
genericAtomicRmwOp : (memref : Value) -> (indices : List Value) -> (atomicBody : Region) -> (result : MlirType) -> Op
genericAtomicRmwOp memref indices atomicBody result =
  MkOp "memref.generic_atomic_rmw" (concat [[memref], indices]) [] [atomicBody] [] [result]

||| `memref.get_global`: get the memref pointing to a global variable
export
getGlobalOp : (name : String) -> (result : MlirType) -> Op
getGlobalOp name result =
  MkOp "memref.get_global" [] [("name", flatSymbolRefAttr name)] [] [] [result]

||| `memref.global`: declare or define a global memref variable
export
globalOp : {default Nothing symVisibility : Maybe String} -> {default Nothing initialValue : Maybe MlirAttr} -> {default False constant : Bool} -> {default Nothing alignment : Maybe Integer} -> (symName : String) -> (type : MlirType) -> Op
globalOp symName type =
  MkOp "memref.global" [] ([("sym_name", stringAttr symName)] ++ attrIf "sym_visibility" stringAttr symVisibility ++ [("type", typeAttr type)] ++ attrIf "initial_value" id initialValue ++ unitIf "constant" constant ++ attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment) [] [] []

||| `memref.load`: load operation
export
loadOp : {default Nothing nontemporal : Maybe Bool} -> {default Nothing alignment : Maybe Integer} -> {default Nothing invariant : Maybe Bool} -> (memref : Value) -> (indices : List Value) -> (result : MlirType) -> Op
loadOp memref indices result =
  MkOp "memref.load" (concat [[memref], indices]) (attrIf "nontemporal" boolAttr nontemporal ++ attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment ++ attrIf "invariant" boolAttr invariant) [] [] [result]

||| `memref.memory_space_cast`: memref memory space cast operation
export
memorySpaceCastOp : (source : Value) -> (dest : MlirType) -> Op
memorySpaceCastOp source dest =
  MkOp "memref.memory_space_cast" [source] [] [] [] [dest]

||| `memref.prefetch`: prefetch operation
export
prefetchOp : (memref : Value) -> (indices : List Value) -> (isWrite : Bool) -> (localityHint : Integer) -> (isDataCache : Bool) -> Op
prefetchOp memref indices isWrite localityHint isDataCache =
  MkOp "memref.prefetch" (concat [[memref], indices]) [("isWrite", boolAttr isWrite), ("localityHint", integerAttr localityHint (integerType 32)), ("isDataCache", boolAttr isDataCache)] [] [] []

||| `memref.rank`: rank operation
export
rankOp : (memref : Value) -> (result0 : MlirType) -> Op
rankOp memref result0 =
  MkOp "memref.rank" [memref] [] [] [] [result0]

||| `memref.realloc`: memory reallocation operation
export
reallocOp : {default Nothing alignment : Maybe Integer} -> (source : Value) -> (dynamicResultSize : Maybe Value) -> (result0 : MlirType) -> Op
reallocOp source dynamicResultSize result0 =
  MkOp "memref.realloc" (concat [[source], toList dynamicResultSize]) (attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment) [] [] [result0]

||| `memref.reinterpret_cast`: memref reinterpret cast operation
export
reinterpretCastOp : (source : Value) -> (offsets : List Value) -> (sizes : List Value) -> (strides : List Value) -> (staticOffsets : MlirAttr) -> (staticSizes : MlirAttr) -> (staticStrides : MlirAttr) -> (result : MlirType) -> Op
reinterpretCastOp source offsets sizes strides staticOffsets staticSizes staticStrides result =
  MkOp "memref.reinterpret_cast" (concat [[source], offsets, sizes, strides]) [("static_offsets", staticOffsets), ("static_sizes", staticSizes), ("static_strides", staticStrides), ("operandSegmentSizes", segmentSizes [1, length offsets, length sizes, length strides])] [] [] [result]

||| `memref.reshape`: memref reshape operation
export
reshapeOp : (source : Value) -> (shape : Value) -> (result : MlirType) -> Op
reshapeOp source shape result =
  MkOp "memref.reshape" [source, shape] [] [] [] [result]

||| `memref.store`: store operation
export
storeOp : {default Nothing nontemporal : Maybe Bool} -> {default Nothing alignment : Maybe Integer} -> (value : Value) -> (memref : Value) -> (indices : List Value) -> Op
storeOp value memref indices =
  MkOp "memref.store" (concat [[value], [memref], indices]) (attrIf "nontemporal" boolAttr nontemporal ++ attrIf "alignment" (\v => integerAttr v (integerType 64)) alignment) [] [] []

||| `memref.subview`: memref subview operation
export
subviewOp : (source : Value) -> (offsets : List Value) -> (sizes : List Value) -> (strides : List Value) -> (staticOffsets : MlirAttr) -> (staticSizes : MlirAttr) -> (staticStrides : MlirAttr) -> (result : MlirType) -> Op
subviewOp source offsets sizes strides staticOffsets staticSizes staticStrides result =
  MkOp "memref.subview" (concat [[source], offsets, sizes, strides]) [("static_offsets", staticOffsets), ("static_sizes", staticSizes), ("static_strides", staticStrides), ("operandSegmentSizes", segmentSizes [1, length offsets, length sizes, length strides])] [] [] [result]

||| `memref.transpose`: `transpose` produces a new strided memref (metadata-only)
export
transposeOp : (in' : Value) -> (permutation : MlirAttr) -> (result0 : MlirType) -> Op
transposeOp in' permutation result0 =
  MkOp "memref.transpose" [in'] [("permutation", permutation)] [] [] [result0]

||| `memref.view`: memref view operation
export
viewOp : (source : Value) -> (byteShift : Value) -> (sizes : List Value) -> (result0 : MlirType) -> Op
viewOp source byteShift sizes result0 =
  MkOp "memref.view" (concat [[source], [byteShift], sizes]) [] [] [] [result0]

-- fingerprint: 2237892245-929710 552575521-12631
