||| The ub dialect, as the Idris side writes it. Generated by
||| idris-mlir-tblgen -gen-idris-dialect from the dialect's ODS; `make build`
||| writes it (tools/dialects.sh). Do not edit.
module IdrisMLIR.Dialect.UB

import IdrisMLIR.MLIR

%default total

------------------------------------------------------------------------------
-- Types and attributes
------------------------------------------------------------------------------

||| `#ub.poison`
export
poisonAttr : MlirAttr
poisonAttr = MkMlirAttr "#ub.poison"

------------------------------------------------------------------------------
-- Ops
------------------------------------------------------------------------------

||| `ub.poison`: Poisoned constant operation.
export
poisonOp : {default Nothing value : Maybe MlirAttr} -> (result : MlirType) -> Op
poisonOp result =
  MkOp "ub.poison" [] (attrIf "value" id value) [] [] [result]

||| `ub.unreachable`: Unreachable operation.
export
unreachableOp : Op
unreachableOp =
  MkOp "ub.unreachable" [] [] [] [] []

-- fingerprint: 2721333293-452019 3464102740-1032
