#!/usr/bin/env python3
"""Generates the power-of-5 tables of the Double printer (LOW-DBL-2).

Ryu (Adams, "Ryu: fast float-to-string conversion", PLDI 2018) needs, for
each i, 5^i and 2^k / 5^i rounded to 125 significant bits. They are computed
here from their definitions with exact integers, and written as the MLIR
globals that foreign/idr/lib/Lower/Runtime.mlir.inc holds between its
GENERATED markers. `--check` verifies that the file matches.

Each entry is two i64 words, low then high, as two's complement.
"""

from pathlib import Path
import sys

POW5_BITCOUNT = 125
POW5_INV_BITCOUNT = 125
SPLIT_SIZE = 326
INV_SPLIT_SIZE = 342
RUNTIME = Path(__file__).resolve().parent.parent / "foreign/idr/lib/Lower/Runtime.mlir.inc"
BEGIN = "  // BEGIN GENERATED by tools/gen_ryu_tables.py; do not edit.\n"
END = "  // END GENERATED\n"


def words(value):
    lo, hi = value & (2**64 - 1), value >> 64
    assert hi < 2**64
    return [w - 2**64 if w >= 2**63 else w for w in (lo, hi)]


def split():
    out = []
    for i in range(SPLIT_SIZE):
        pow5 = 5**i
        shift = pow5.bit_length() - POW5_BITCOUNT
        out += words(pow5 >> shift if shift >= 0 else pow5 << -shift)
    return out


def inv_split():
    out = []
    for i in range(INV_SPLIT_SIZE):
        pow5 = 5**i
        j = pow5.bit_length() - 1 + POW5_INV_BITCOUNT
        out += words((1 << j) // pow5 + 1)
    return out


def glob(name, values):
    n = len(values)
    body = ", ".join(str(v) for v in values)
    return (f"  llvm.mlir.global internal constant @{name}(dense<[{body}]> : tensor<{n}xi64>)"
            f" : !llvm.array<{n} x i64>\n")


def generated():
    return BEGIN + glob("__idr_ryu_pow5_split", split()) + \
        glob("__idr_ryu_pow5_inv_split", inv_split()) + END


def main():
    text = RUNTIME.read_text()
    start, end = text.index(BEGIN), text.index(END) + len(END)
    new = text[:start] + generated() + text[end:]
    if "--check" in sys.argv:
        if new != text:
            sys.exit("Runtime.mlir.inc tables are stale: run tools/gen_ryu_tables.py")
        return
    RUNTIME.write_text(new)


if __name__ == "__main__":
    main()
