||| Generates the power-of-5 tables of the Double printer (LOW-DBL-2).
|||
||| Ryu (Adams, "Ryu: fast float-to-string conversion", PLDI 2018) needs, for
||| each i, 5^i and 2^k / 5^i rounded to 125 significant bits. They are
||| computed here from their definitions with exact integers, and written as
||| the MLIR globals that foreign/idr/lib/Lower/Runtime.mlir.inc holds between
||| its GENERATED markers. `--check` verifies that the file matches.
|||
||| Each entry is two i64 words, low then high, as two's complement.
|||
||| Usage, from `make ryu-tables` and the `toolchain/ryu-tables` test:
|||
|||     gen-ryu-tables [--check] foreign/idr/lib/Lower/Runtime.mlir.inc
module GenRyuTables

import Data.Bits
import Data.List
import Data.List1
import Data.String
import System
import System.File

%default covering

pow5Bitcount : Integer
pow5Bitcount = 125

pow5InvBitcount : Integer
pow5InvBitcount = 125

splitSize : Nat
splitSize = 326

invSplitSize : Nat
invSplitSize = 342

||| The first line of the generated region. Only its prefix is searched for,
||| so the line names whichever generator wrote it last.
beginPrefix : String
beginPrefix = "  // BEGIN GENERATED"

begin : String
begin = "  // BEGIN GENERATED by tools/GenRyuTables.idr (make ryu-tables); do not edit."

end : String
end = "  // END GENERATED"

twoTo : Integer -> Integer
twoTo k = shiftL 1 (integerToNat k)

power5 : Nat -> Integer
power5 Z = 1
power5 (S k) = 5 * power5 k

||| The number of bits of a positive integer, Python's `int.bit_length`.
bitLength : Integer -> Integer
bitLength n = go n 0
  where
    go : Integer -> Integer -> Integer
    go m acc = if m <= 0 then acc else go (m `div` 2) (acc + 1)

||| Low and high i64 words, as two's complement.
i64Words : Integer -> List Integer
i64Words value =
  let lo = value .&. (twoTo 64 - 1)
      hi = shiftR value 64
  in if hi >= twoTo 64
        then assert_total (idris_crash "a table entry does not fit in 128 bits")
        else map signed [lo, hi]
  where
    signed : Integer -> Integer
    signed w = if w >= twoTo 63 then w - twoTo 64 else w

||| 0, 1, ..., n - 1.
indices : Nat -> List Nat
indices n = go n []
  where
    go : Nat -> List Nat -> List Nat
    go Z acc = acc
    go (S k) acc = go k (k :: acc)

pow5Split : List Integer
pow5Split = concatMap entry (indices splitSize)
  where
    entry : Nat -> List Integer
    entry i =
      let pow5 = power5 i
          shift = bitLength pow5 - pow5Bitcount
      in i64Words (if shift >= 0
                   then shiftR pow5 (integerToNat shift)
                   else shiftL pow5 (integerToNat (negate shift)))

pow5InvSplit : List Integer
pow5InvSplit = concatMap entry (indices invSplitSize)
  where
    entry : Nat -> List Integer
    entry i =
      let pow5 = power5 i
          j = bitLength pow5 - 1 + pow5InvBitcount
      in i64Words (twoTo j `div` pow5 + 1)

glob : String -> List Integer -> String
glob name values =
  let n = show (length values)
  in "  llvm.mlir.global internal constant @" ++ name ++ "(dense<["
       ++ joinBy ", " (map show values) ++ "]> : tensor<" ++ n ++ "xi64>)"
       ++ " : !llvm.array<" ++ n ++ " x i64>"

generated : List String
generated =
  [ begin
  , glob "__idr_ryu_pow5_split" pow5Split
  , glob "__idr_ryu_pow5_inv_split" pow5InvSplit
  , end
  ]

||| The file with its generated region replaced, or Nothing without markers.
regenerate : String -> Maybe String
regenerate text = do
  let ls = forget (split (== '\n') text)
  b <- findIndex (isPrefixOf beginPrefix) ls
  let rest = drop (finToNat b) ls
  e <- findIndex (== end) rest
  pure $ joinBy "\n"
    (take (finToNat b) ls ++ generated ++ drop (S (finToNat e)) rest)

fail : String -> IO a
fail message = do
  ignore $ fPutStrLn stderr message
  exitWith (ExitFailure 1)

main : IO ()
main = do
  (check, path) <- case !getArgs of
    [_, "--check", path] => pure (True, path)
    [_, path] => pure (False, path)
    _ => fail "usage: gen-ryu-tables [--check] Runtime.mlir.inc"
  Right text <- readFile path
    | Left err => fail "\{path}: \{show err}"
  let Just new = regenerate text
    | Nothing => fail "\{path}: no GENERATED markers"
  if check
     then unless (new == text) $
            fail "Runtime.mlir.inc tables are stale: run make ryu-tables"
     else do Right () <- writeFile path new
               | Left err => fail "\{path}: \{show err}"
             pure ()
