// idr.mlir: MLIR, LLVM and the idr dialect's TableGen-generated
// declarations, for module units to import. Their headers are parsed here,
// once; a unit that included them itself would parse them again, and one
// that included them after an import would clash with this module's copy
// of them. MLIR's API is headers only and exports nothing, so this module
// names what idr's code uses and re-exports it: each `using` below makes a
// declaration of the global module fragment visible to importers.
// Operators are re-exported too, so that lookup by argument finds them.
module;
#include "idr/Idr.h"

#include "mlir/Analysis/CallGraph.h"
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
#include "mlir/Analysis/DataFlow/SparseAnalysis.h"
#include "mlir/Analysis/DataFlow/Utils.h"
#include "mlir/Analysis/DataFlowFramework.h"
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Conversion/ConvertToLLVM/ToLLVMPass.h"
#include "mlir/Conversion/ReconcileUnrealizedCasts/ReconcileUnrealizedCasts.h"
#include "mlir/Conversion/SCFToControlFlow/SCFToControlFlow.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlow.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Transforms/FuncConversions.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Patterns.h"
#include "mlir/Dialect/UB/IR/UBOps.h"
#include "mlir/IR/Action.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Remarks.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/IR/Unit.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/InferIntRangeInterface.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassRegistry.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Support/TypeID.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Inliner.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/RegionUtils.h"

#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/STLFunctionalExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/SHA1.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/raw_ostream.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <concepts>
#include <cstdint>
#include <cstring>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <variant>
#include <vector>

export module idr.mlir;

export namespace mlir {
using mlir::AnalysisState;
using mlir::any;
using mlir::APFloat;
using mlir::APInt;
using mlir::applyPartialConversion;
using mlir::applyPatternsGreedily;
using mlir::APSInt;
using mlir::ArrayAttr;
using mlir::ArrayRef;
using mlir::AsmParser;
using mlir::AsmPrinter;
using mlir::Attribute;
using mlir::BitVector;
using mlir::Block;
using mlir::BlockArgument;
using mlir::BoolAttr;
using mlir::Builder;
using mlir::BytecodeOpInterface;
using mlir::CallableOpInterface;
using mlir::CallGraph;
using mlir::CallOpInterface;
using mlir::CallSiteLoc;
using mlir::cast;
using mlir::ChangeResult;
using mlir::ConstantIntRanges;
using mlir::ConversionConfig;
using mlir::ConversionPatternRewriter;
using mlir::ConversionTarget;
using mlir::createCanonicalizerPass;
using mlir::createConvertToLLVMPass;
using mlir::createCSEPass;
using mlir::createReconcileUnrealizedCastsPass;
using mlir::createSCFToControlFlowPass;
using mlir::DataFlowConfig;
using mlir::DataFlowSolver;
using mlir::DenseElementsAttr;
using mlir::DenseMap;
using mlir::DenseSet;
using mlir::Dialect;
using mlir::DialectInlinerInterface;
using mlir::DialectRegistry;
using mlir::DictionaryAttr;
using mlir::dyn_cast;
using mlir::dyn_cast_or_null;
using mlir::emitError;
using mlir::emitRemark;
using mlir::failed;
using mlir::failure;
using mlir::FailureOr;
using mlir::FileLineColLoc;
using mlir::FlatSymbolRefAttr;
using mlir::Float64Type;
using mlir::FloatAttr;
using mlir::FloatType;
using mlir::FrozenRewritePatternSet;
using mlir::function_ref;
using mlir::FunctionOpInterface;
using mlir::FunctionType;
using mlir::FusedLoc;
using mlir::GenericLatticeAnchorBase;
using mlir::get;
using mlir::getType;
using mlir::GreedyRewriteConfig;
using mlir::GreedySimplifyRegionLevel;
using mlir::InferIntRangeInterface;
using mlir::InferTypeOpInterface;
using mlir::InFlightDiagnostic;
using mlir::Inliner;
using mlir::InlinerConfig;
using mlir::IntegerAttr;
using mlir::IntegerType;
using mlir::InvocationBounds;
using mlir::IRMapping;
using mlir::IRRewriter;
using mlir::IRUnit;
using mlir::isa;
using mlir::isa_and_nonnull;
using mlir::Location;
using mlir::LocationAttr;
using mlir::LogicalResult;
using mlir::m_Constant;
using mlir::m_ConstantInt;
using mlir::matchPattern;
using mlir::MemoryEffectOpInterface;
using mlir::MLIRContext;
using mlir::ModuleAnalysisManager;
using mlir::ModuleOp;
using mlir::MutableArrayRef;
using mlir::NamedAttribute;
using mlir::NamedAttrList;
using mlir::NameLoc;
using mlir::NoneType;
using mlir::NonSuccessorInputReplacementBuilderFn;
using mlir::OpAsmParser;
using mlir::OpAsmPrinter;
using mlir::OpBuilder;
using mlir::OpConversionPattern;
using mlir::OperandRange;
using mlir::Operation;
using mlir::OperationEquivalence;
using mlir::OperationName;
using mlir::OperationState;
using mlir::OpFoldResult;
using mlir::OpOperand;
using mlir::OpPassManager;
using mlir::OpResult;
using mlir::OpRewritePattern;
using mlir::OwningOpRef;
using mlir::parsePassPipeline;
using mlir::ParseResult;
using mlir::parseSourceFile;
using mlir::Pass;
using mlir::PassManager;
using mlir::PassPipelineRegistration;
using mlir::Pattern;
using mlir::PatternRewriter;
using mlir::populateCallOpTypeConversionPattern;
using mlir::populateFunctionOpInterfaceTypeConversionPattern;
using mlir::populateRegionBranchOpInterfaceCanonicalizationPatterns;
using mlir::populateRegionBranchOpInterfaceInliningPattern;
using mlir::populateReturnOpTypeConversionPattern;
using mlir::ProgramPoint;
using mlir::RankedTensorType;
using mlir::raw_ostream;
using mlir::Region;
using mlir::RegionBranchOpInterface;
using mlir::RegionBranchPoint;
using mlir::RegionBranchSuccessorMapping;
using mlir::RegionBranchTerminatorOpInterface;
using mlir::RegionSuccessor;
using mlir::RegisteredOperationName;
using mlir::ResultRange;
using mlir::RewritePatternSet;
using mlir::RewriterBase;
using mlir::SetIntRangeFn;
using mlir::SetVector;
using mlir::SmallVector;
using mlir::SmallVectorImpl;
using mlir::SMLoc;
using mlir::StringAttr;
using mlir::StringLiteral;
using mlir::StringRef;
using mlir::StringSet;
using mlir::StringSwitch;
using mlir::succeeded;
using mlir::success;
using mlir::SymbolRefAttr;
using mlir::SymbolTable;
using mlir::SymbolTableCollection;
using mlir::TokenType;
using mlir::toString;
using mlir::Twine;
using mlir::Type;
using mlir::TypeAttr;
using mlir::TypeConverter;
using mlir::TypedAttr;
using mlir::TypeID;
using mlir::TypeRange;
using mlir::TypeSwitch;
using mlir::UnitAttr;
using mlir::UnknownLoc;
using mlir::UnrealizedConversionCastOp;
using mlir::Value;
using mlir::ValueRange;
using mlir::visitUsedValuesDefinedAbove;
using mlir::WalkOrder;
using mlir::WalkResult;
using mlir::operator!;
using mlir::operator!=;
using mlir::operator&;
using mlir::operator&=;
using mlir::operator*;
using mlir::operator+;
using mlir::operator-;
using mlir::operator/;
using mlir::operator<<;
using mlir::operator<<=;
using mlir::operator==;
using mlir::operator>>;
using mlir::operator>>=;
using mlir::operator^;
using mlir::operator^=;
using mlir::operator|;
using mlir::operator|=;
using mlir::operator~;
} // namespace mlir

export namespace mlir::LLVM {
using mlir::LLVM::AddressOfOp;
using mlir::LLVM::AllocaOp;
using mlir::LLVM::AndOp;
using mlir::LLVM::bitEnumContainsAny;
using mlir::LLVM::CallIntrinsicOp;
using mlir::LLVM::CallOp;
using mlir::LLVM::ConstantOp;
using mlir::LLVM::GEPArg;
using mlir::LLVM::GEPOp;
using mlir::LLVM::GlobalOp;
using mlir::LLVM::ICmpOp;
using mlir::LLVM::ICmpPredicate;
using mlir::LLVM::InsertValueOp;
using mlir::LLVM::IntToPtrOp;
using mlir::LLVM::Linkage;
using mlir::LLVM::LLVMArrayType;
using mlir::LLVM::LLVMDialect;
using mlir::LLVM::LLVMFuncOp;
using mlir::LLVM::LLVMFunctionType;
using mlir::LLVM::LLVMPointerType;
using mlir::LLVM::LLVMStructType;
using mlir::LLVM::LLVMVoidType;
using mlir::LLVM::LoadOp;
using mlir::LLVM::PoisonAttr;
using mlir::LLVM::PoisonOp;
using mlir::LLVM::PtrToIntOp;
using mlir::LLVM::ReturnOp;
using mlir::LLVM::SelectOp;
using mlir::LLVM::StoreOp;
using mlir::LLVM::UnreachableOp;
using mlir::LLVM::ZeroOp;
using mlir::LLVM::operator&;
using mlir::LLVM::operator&=;
using mlir::LLVM::operator^;
using mlir::LLVM::operator^=;
using mlir::LLVM::operator|;
using mlir::LLVM::operator|=;
using mlir::LLVM::operator~;
} // namespace mlir::LLVM

export namespace mlir::MemoryEffects {
using mlir::MemoryEffects::Allocate;
using mlir::MemoryEffects::Effect;
using mlir::MemoryEffects::EffectInstance;
using mlir::MemoryEffects::Free;
using mlir::MemoryEffects::Write;
} // namespace mlir::MemoryEffects

export namespace mlir::OpTrait {
using mlir::OpTrait::ConstantLike;
using mlir::OpTrait::HasRecursiveMemoryEffects;
using mlir::OpTrait::IsTerminator;
using mlir::OpTrait::SymbolTable;
using mlir::OpTrait::TraitBase;
} // namespace mlir::OpTrait

export namespace mlir::SideEffects {
using mlir::SideEffects::AutomaticAllocationScopeResource;
using mlir::SideEffects::DefaultResource;
using mlir::SideEffects::Effect;
using mlir::SideEffects::EffectInstance;
using mlir::SideEffects::Resource;
} // namespace mlir::SideEffects

export namespace mlir::Speculation {
using mlir::Speculation::Speculatability;
} // namespace mlir::Speculation

export namespace mlir::arith {
using mlir::arith::AddIOp;
using mlir::arith::AndIOp;
using mlir::arith::ArithDialect;
using mlir::arith::bitEnumContainsAny;
using mlir::arith::CmpIOp;
using mlir::arith::CmpIPredicate;
using mlir::arith::ConstantIndexOp;
using mlir::arith::ConstantOp;
using mlir::arith::DivSIOp;
using mlir::arith::DivUIOp;
using mlir::arith::ExtSIOp;
using mlir::arith::ExtUIOp;
using mlir::arith::IndexCastOp;
using mlir::arith::IndexCastUIOp;
using mlir::arith::OrIOp;
using mlir::arith::RemSIOp;
using mlir::arith::RemUIOp;
using mlir::arith::SelectOp;
using mlir::arith::SubIOp;
using mlir::arith::TruncIOp;
using mlir::arith::XOrIOp;
using mlir::arith::operator&;
using mlir::arith::operator&=;
using mlir::arith::operator^;
using mlir::arith::operator^=;
using mlir::arith::operator|;
using mlir::arith::operator|=;
using mlir::arith::operator~;
} // namespace mlir::arith

export namespace mlir::cf {
using mlir::cf::ControlFlowDialect;
} // namespace mlir::cf

export namespace mlir::dataflow {
using mlir::dataflow::AbstractSparseForwardDataFlowAnalysis;
using mlir::dataflow::AbstractSparseLattice;
using mlir::dataflow::DeadCodeAnalysis;
using mlir::dataflow::Executable;
using mlir::dataflow::Lattice;
using mlir::dataflow::loadBaselineAnalyses;
using mlir::dataflow::PredecessorState;
using mlir::dataflow::SparseForwardDataFlowAnalysis;
} // namespace mlir::dataflow

export namespace mlir::func {
using mlir::func::CallIndirectOp;
using mlir::func::CallOp;
using mlir::func::ConstantOp;
using mlir::func::FuncOp;
using mlir::func::ReturnOp;
} // namespace mlir::func

export namespace mlir::math {
using mlir::math::IsFiniteOp;
using mlir::math::MathDialect;
} // namespace mlir::math

export namespace mlir::remark {
using mlir::remark::add;
using mlir::remark::analysis;
using mlir::remark::metric;
using mlir::remark::missed;
using mlir::remark::passed;
using mlir::remark::reason;
using mlir::remark::RemarkOpts;
} // namespace mlir::remark

export namespace mlir::scf {
using mlir::scf::ConditionOp;
using mlir::scf::IfOp;
using mlir::scf::IndexSwitchOp;
using mlir::scf::populateSCFStructuralTypeConversionsAndLegality;
using mlir::scf::WhileOp;
using mlir::scf::YieldOp;
} // namespace mlir::scf

export namespace mlir::tracing {
using mlir::tracing::Action;
using mlir::tracing::ActionImpl;
} // namespace mlir::tracing

export namespace mlir::ub {
using mlir::ub::PoisonAttr;
using mlir::ub::PoisonAttrInterface;
using mlir::ub::PoisonOp;
using mlir::ub::UnreachableOp;
} // namespace mlir::ub

export namespace llvm {
using llvm::alignTo;
using llvm::all_of;
using llvm::all_of_zip;
using llvm::any;
using llvm::any_of;
using llvm::APFloat;
using llvm::APInt;
using llvm::append_range;
using llvm::APSInt;
using llvm::Argument;
using llvm::ArrayRef;
using llvm::bit_cast;
using llvm::BitVector;
using llvm::cast;
using llvm::Constant;
using llvm::copy;
using llvm::count;
using llvm::count_if;
using llvm::DenseMap;
using llvm::DenseSet;
using llvm::dyn_cast;
using llvm::dyn_cast_or_null;
using llvm::enumerate;
using llvm::equal;
using llvm::erase;
using llvm::Error;
using llvm::errs;
using llvm::exp;
using llvm::failed;
using llvm::failure;
using llvm::FailureOr;
using llvm::fill;
using llvm::find;
using llvm::for_each;
using llvm::formatv;
using llvm::function_ref;
using llvm::get;
using llvm::getToken;
using llvm::identity;
using llvm::InitializeNativeTarget;
using llvm::InitializeNativeTargetAsmPrinter;
using llvm::IntegerType;
using llvm::interleaveComma;
using llvm::is_contained;
using llvm::is_one_of;
using llvm::isa;
using llvm::isa_and_nonnull;
using llvm::IsaPred;
using llvm::isDigit;
using llvm::join;
using llvm::LLVMContext;
using llvm::LogicalResult;
using llvm::make_early_inc_range;
using llvm::make_filter_range;
using llvm::make_range;
using llvm::map_to_vector;
using llvm::MapVector;
using llvm::Module;
using llvm::move;
using llvm::MutableArrayRef;
using llvm::nodes;
using llvm::none_of;
using llvm::ParseResult;
using llvm::PowerOf2Ceil;
using llvm::raw_ostream;
using llvm::raw_string_ostream;
using llvm::replace;
using llvm::report_fatal_error;
using llvm::reverse;
using llvm::scope_exit;
using llvm::SetVector;
using llvm::SHA1;
using llvm::size;
using llvm::SmallDenseSet;
using llvm::SmallVector;
using llvm::SmallVectorImpl;
using llvm::SMLoc;
using llvm::sort;
using llvm::split;
using llvm::Statistic;
using llvm::StringLiteral;
using llvm::StringMap;
using llvm::StringRef;
using llvm::StringSet;
using llvm::StringSwitch;
using llvm::succeeded;
using llvm::success;
using llvm::to_vector;
using llvm::toString;
using llvm::transform;
using llvm::Twine;
using llvm::Type;
using llvm::TypeSwitch;
using llvm::unique;
using llvm::Use;
using llvm::Value;
using llvm::zip;
using llvm::zip_equal;
using llvm::operator!;
using llvm::operator!=;
using llvm::operator&;
using llvm::operator&=;
using llvm::operator*;
using llvm::operator+;
using llvm::operator+=;
using llvm::operator-;
using llvm::operator<;
using llvm::operator<<;
using llvm::operator<<=;
using llvm::operator<=;
using llvm::operator==;
using llvm::operator>;
using llvm::operator>=;
using llvm::operator>>;
using llvm::operator>>=;
using llvm::operator^;
using llvm::operator^=;
using llvm::operator|;
using llvm::operator|=;
using llvm::operator~;
} // namespace llvm

export namespace idr {
using idr::ApplyOp;
using idr::BigAddOp;
using idr::BigAndOp;
using idr::BigAttr;
using idr::BigCmpOp;
using idr::BigDivOp;
using idr::BigFromDoubleOp;
using idr::BigFromIntOp;
using idr::BigSmallOp;
using idr::BigFromStrOp;
using idr::BigModOp;
using idr::BigMulOp;
using idr::BigNegOp;
using idr::BigOrOp;
using idr::BigPredOp;
using idr::BigShowOp;
using idr::BigSubOp;
using idr::BigToDoubleOp;
using idr::BigToIntOp;
using idr::BigType;
using idr::BigXorOp;
using idr::bitEnumContainsAny;
using idr::BoxType;
using idr::CallsRuntime;
using idr::CloneAttr;
using idr::ClosureAttr;
using idr::ClosureOp;
using idr::CmpPredicate;
using idr::ConAttr;
using idr::ConOp;
using idr::ConstantOp;
using idr::CrashOp;
using idr::CrashResource;
using idr::createIdrLower;
using idr::CtorOp;
using idr::DataOp;
using idr::DataType;
using idr::DecOp;
using idr::DivergenceResource;
using idr::DivOp;
using idr::DoubleHeadOp;
using idr::Effect;
using idr::EffectAttr;
using idr::ErasedAttr;
using idr::erased;
using idr::Grade;
using idr::gradeOf;
using idr::graded;
using idr::isErased;
using idr::isLinear;
using idr::isWorld;
using idr::FieldOp;
using idr::FnType;
using idr::GetByteOp;
using idr::getSumName;
using idr::IdrDialect;
using idr::IdrLowerOptions;
using idr::IncOp;
using idr::IntHeadOp;
using idr::IOResource;
using idr::isFieldType;
using idr::KeyApplyAttr;
using idr::KeyApplyFieldAttr;
using idr::KeyClosureAttr;
using idr::KeyConAttr;
using idr::KeyHoleAttr;
using idr::knownFinite;
using idr::knownNonEmpty;
using idr::knownNonZero;
using idr::LinEnterOp;
using idr::LinResource;
using idr::linear;
using idr::Permission;
using idr::QType;
using idr::LinUseOp;
using idr::lookupCtor;
using idr::lookupData;
using idr::MatchLitOp;
using idr::MatchOp;
using idr::MayCrash;
using idr::MayCrashOpInterface;
using idr::MayLoopOp;
using idr::ModOp;
using idr::NatFromBigOp;
using idr::NatToBigOp;
using idr::NatType;
using idr::PerformsIO;
using idr::pipelineSteps;
using idr::PutCharOp;
using idr::PutDoubleOp;
using idr::PutIntOp;
using idr::PutStrOp;
using idr::Quantity;
using idr::quantityOf;
using idr::readOnce;
using idr::registerIdr;
using idr::registerIdrPasses;
using idr::registerIdrPipeline;
using idr::ReuseOp;
using idr::SpecKeyAttr;
using idr::StrAppendOp;
using idr::StrCmpOp;
using idr::StrConsOp;
using idr::StrFromCharOp;
using idr::StrHeadOp;
using idr::StrIndexOp;
using idr::StrLengthOp;
using idr::StrReverseOp;
using idr::StrShowOp;
using idr::StrSubstrOp;
using idr::StrTailOp;
using idr::StrToDoubleOp;
using idr::StrToIntOp;
using idr::StrType;
using idr::TagOp;
using idr::TakeOp;
using idr::throughLinear;
using idr::ToCharOp;
using idr::ToIntOp;
using idr::TokenType;
using idr::unrestricted;
using idr::WorldType;
using idr::YieldOp;
using idr::operator&;
using idr::operator&=;
using idr::operator^;
using idr::operator^=;
using idr::operator|;
using idr::operator|=;
using idr::operator~;
} // namespace idr

// Re-exports only, as libc++'s own std module does: nothing is added to
// std.
// NOLINTBEGIN(bugprone-std-namespace-modification)
export namespace std {
using std::acos;
using std::advance;
using std::all_of;
using std::any_of;
using std::apply;
using std::arg;
using std::array;
using std::asin;
using std::atan;
using std::back_inserter;
using std::begin;
using std::bind;
using std::bit_cast;
using std::byte;
using std::ceil;
using std::convertible_to;
using std::copy;
using std::cos;
using std::count;
using std::count_if;
using std::ctime;
using std::data;
using std::dec;
using std::empty;
using std::end;
using std::ends;
using std::equal;
using std::erase;
using std::exit;
using std::exp;
using std::exp2;
using std::fill;
using std::find;
using std::fixed;
using std::floor;
using std::fmod;
using std::for_each;
using std::free;
using std::function;
using std::get;
using std::get_if;
using std::holds_alternative;
using std::identity;
using std::int32_t;
using std::int64_t;
using std::internal;
using std::iterator;
using std::ldexp;
using std::left;
using std::log;
using std::make_pair;
using std::make_shared;
using std::make_tuple;
using std::make_unique;
using std::map;
using std::max;
using std::memcpy;
using std::memmove;
using std::memset;
using std::milli;
using std::min;
using std::minus;
using std::move;
using std::next;
using std::none_of;
using std::nullopt;
using std::nullopt_t;
using std::numeric_limits;
using std::optional;
using std::pair;
using std::plus;
using std::pow;
using std::predicate;
using std::prev;
using std::ref;
using std::remove;
using std::replace;
using std::reverse;
using std::round;
using std::set;
using std::set_union;
using std::shared_ptr;
using std::sin;
using std::size;
using std::size_t;
using std::sort;
using std::sqrt;
using std::strerror;
using std::string;
using std::tan;
using std::time;
using std::timespec;
using std::to_string;
using std::transform;
using std::trunc;
using std::tuple;
using std::uint32_t;
using std::uint64_t;
using std::uint8_t;
using std::uintptr_t;
using std::unique;
using std::unique_ptr;
using std::unreachable;
using std::variant;
using std::vector;
using std::visit;
using std::operator!=;
using std::operator&;
using std::operator&=;
using std::operator*;
using std::operator+;
using std::operator-;
using std::operator/;
using std::operator<;
using std::operator<<;
using std::operator<<=;
using std::operator<=;
using std::operator<=>;
using std::operator==;
using std::operator>;
using std::operator>=;
using std::operator>>;
using std::operator>>=;
using std::operator^;
using std::operator^=;
using std::operator|;
using std::operator|=;
using std::operator~;
} // namespace std

export namespace std::chrono {
using std::chrono::ceil;
using std::chrono::duration;
using std::chrono::floor;
using std::chrono::nanoseconds;
using std::chrono::round;
using std::chrono::steady_clock;
using std::chrono::operator%;
using std::chrono::operator*;
using std::chrono::operator+;
using std::chrono::operator-;
using std::chrono::operator/;
using std::chrono::operator<;
using std::chrono::operator<=;
using std::chrono::operator<=>;
using std::chrono::operator==;
using std::chrono::operator>;
using std::chrono::operator>=;
} // namespace std::chrono

export namespace std::ranges {
using std::ranges::advance;
using std::ranges::all_of;
using std::ranges::any_of;
using std::ranges::begin;
using std::ranges::contains;
using std::ranges::copy;
using std::ranges::count;
using std::ranges::count_if;
using std::ranges::data;
using std::ranges::empty;
using std::ranges::end;
using std::ranges::ends_with;
using std::ranges::equal;
using std::ranges::fill;
using std::ranges::find;
using std::ranges::for_each;
using std::ranges::get;
using std::ranges::max;
using std::ranges::min;
using std::ranges::move;
using std::ranges::next;
using std::ranges::none_of;
using std::ranges::prev;
using std::ranges::range;
using std::ranges::remove;
using std::ranges::replace;
using std::ranges::reverse;
using std::ranges::set_union;
using std::ranges::size;
using std::ranges::sort;
using std::ranges::starts_with;
using std::ranges::transform;
using std::ranges::unique;
using std::ranges::operator|;
} // namespace std::ranges

export namespace std::ranges::views {
using std::ranges::views::all;
using std::ranges::views::reverse;
} // namespace std::ranges::views
// NOLINTEND(bugprone-std-namespace-modification)
